window.JSB_LEGAL_DATABASE = [
  {
    id: "cf-225",
    title: "Constituição Federal — art. 225",
    scope: "Federal",
    uf: "BR",
    authority: "Presidência da República",
    themes: ["licenciamento", "fauna", "flora", "supressao", "biodiversidade"],
    keywords: ["meio ambiente", "fauna", "flora", "degradacao", "impacto ambiental", "estudo previo"],
    summary: "Estabelece o direito ao meio ambiente ecologicamente equilibrado e impõe ao Poder Público e à coletividade o dever de defendê-lo e preservá-lo, incluindo proteção da fauna e flora e exigência de estudo prévio de impacto ambiental para atividades potencialmente causadoras de significativa degradação.",
    relevance: "É a base constitucional para proteção ambiental, licenciamento, fauna, flora e avaliação de impactos.",
    url: "https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm",
    verified: "out/2026"
  },
  {
    id: "lei-5197-1967",
    title: "Lei nº 5.197/1967 — Proteção à Fauna",
    scope: "Federal",
    uf: "BR",
    authority: "Presidência da República",
    themes: ["fauna", "resgate", "manejo", "captura", "salvamento"],
    keywords: ["fauna silvestre", "captura", "apanha", "perseguicao", "animais silvestres"],
    summary: "Dispõe sobre a proteção da fauna silvestre e estabelece regras gerais para utilização, perseguição, destruição, caça ou apanha de animais silvestres.",
    relevance: "É uma das referências federais centrais para atividades que envolvam manejo de fauna silvestre.",
    url: "https://www.planalto.gov.br/ccivil_03/leis/l5197compilado.htm",
    verified: "out/2026"
  },
  {
    id: "lei-6938-1981",
    title: "Lei nº 6.938/1981 — Política Nacional do Meio Ambiente",
    scope: "Federal",
    uf: "BR",
    authority: "Presidência da República",
    themes: ["licenciamento", "impacto", "gestao ambiental"],
    keywords: ["politica nacional meio ambiente", "sisnama", "licenciamento", "poluidor", "degradacao"],
    summary: "Institui a Política Nacional do Meio Ambiente, estrutura o Sisnama e estabelece instrumentos de gestão ambiental, entre eles o licenciamento.",
    relevance: "Ajuda a contextualizar o licenciamento e a atuação dos órgãos ambientais.",
    url: "https://www.planalto.gov.br/ccivil_03/leis/l6938compilada.htm",
    verified: "out/2026"
  },
  {
    id: "lei-9605-1998",
    title: "Lei nº 9.605/1998 — Lei de Crimes Ambientais",
    scope: "Federal",
    uf: "BR",
    authority: "Presidência da República",
    themes: ["fauna", "flora", "supressao", "responsabilidade"],
    keywords: ["crime ambiental", "fauna", "flora", "corte arvore", "captura", "autorizacao"],
    summary: "Dispõe sobre sanções penais e administrativas derivadas de condutas e atividades lesivas ao meio ambiente, incluindo condutas contra a fauna e a flora.",
    relevance: "É relevante quando a atividade pode depender de autorização ambiental ou envolver fauna e vegetação protegidas.",
    url: "https://www.planalto.gov.br/ccivil_03/leis/l9605.htm",
    verified: "out/2026"
  },
  {
    id: "decreto-6514-2008",
    title: "Decreto nº 6.514/2008 — Infrações e Sanções Administrativas Ambientais",
    scope: "Federal",
    uf: "BR",
    authority: "Presidência da República",
    themes: ["fauna", "flora", "supressao", "responsabilidade"],
    keywords: ["infracao ambiental", "multa", "fauna", "flora", "desmatamento", "supressao"],
    summary: "Regulamenta infrações e sanções administrativas ambientais federais e trata de condutas relacionadas à fauna, flora e outras formas de degradação ambiental.",
    relevance: "Ajuda a identificar consequências administrativas de intervenções ambientais executadas em desacordo com a legislação.",
    url: "https://www.planalto.gov.br/ccivil_03/_ato2007-2010/2008/decreto/d6514.htm",
    verified: "out/2026"
  },
  {
    id: "lc-140-2011",
    title: "Lei Complementar nº 140/2011",
    scope: "Federal",
    uf: "BR",
    authority: "Presidência da República",
    themes: ["competencia", "licenciamento", "fauna", "flora", "supressao"],
    keywords: ["competencia", "uniao", "estado", "municipio", "licenciamento", "autorizacao ambiental"],
    summary: "Organiza a cooperação administrativa entre União, Estados, Distrito Federal e Municípios nas ações de proteção ambiental e ajuda a definir qual ente atua no licenciamento e em autorizações ambientais.",
    relevance: "É fundamental para entender por que a localização do empreendimento, sozinha, não define qual órgão será competente.",
    url: "https://www.planalto.gov.br/ccivil_03/leis/lcp/lcp140.htm",
    verified: "out/2026"
  },
  {
    id: "lei-12651-2012",
    title: "Lei nº 12.651/2012 — Proteção da Vegetação Nativa",
    scope: "Federal",
    uf: "BR",
    authority: "Presidência da República",
    themes: ["flora", "supressao", "vegetacao", "app", "reserva legal"],
    keywords: ["arvore", "arvores", "vegetacao nativa", "supressao vegetal", "app", "reserva legal", "imovel rural"],
    summary: "Dispõe sobre a proteção da vegetação nativa e estabelece regras relacionadas a Áreas de Preservação Permanente, Reserva Legal e intervenções em vegetação.",
    relevance: "É uma referência importante quando a dúvida envolve corte ou supressão de vegetação nativa, especialmente em APP, Reserva Legal ou imóvel rural.",
    url: "https://www.planalto.gov.br/ccivil_03/_ato2011-2014/2012/lei/l12651.htm",
    verified: "out/2026"
  },
  {
    id: "lei-11428-2006",
    title: "Lei nº 11.428/2006 — Lei da Mata Atlântica",
    scope: "Federal",
    uf: "BR",
    authority: "Presidência da República",
    themes: ["flora", "supressao", "vegetacao", "mata atlantica"],
    keywords: ["mata atlantica", "vegetacao", "supressao", "corte", "arvore", "arvores"],
    summary: "Dispõe sobre a utilização e proteção da vegetação nativa do Bioma Mata Atlântica e estabelece regras específicas para supressão e intervenção quando o bioma for aplicável.",
    relevance: "Pode ser determinante em terrenos inseridos no Bioma Mata Atlântica ou em formações vegetais abrangidas pela lei.",
    url: "https://www.planalto.gov.br/ccivil_03/_ato2004-2006/2006/lei/l11428.htm",
    verified: "out/2026"
  },
  {
    id: "lei-15190-2025",
    title: "Lei nº 15.190/2025 — Lei Geral do Licenciamento Ambiental",
    scope: "Federal",
    uf: "BR",
    authority: "Presidência da República",
    themes: ["licenciamento", "empreendimento", "estudos ambientais"],
    keywords: ["licenciamento ambiental", "obra", "empreendimento", "farmacia", "construcao", "estudo ambiental"],
    summary: "Estabelece normas gerais para o licenciamento ambiental no Brasil e disciplina modalidades, estudos, procedimentos e responsabilidades aplicáveis ao processo.",
    relevance: "É uma referência geral para dúvidas sobre implantação de empreendimentos e necessidade de licenciamento ambiental.",
    url: "https://www.planalto.gov.br/ccivil_03/_ato2023-2026/2025/lei/l15190.htm",
    verified: "out/2026"
  },
  {
    id: "in-ibama-146-2007",
    title: "IN Ibama nº 146/2007",
    scope: "Federal",
    uf: "BR",
    authority: "Ibama",
    themes: ["fauna", "resgate", "salvamento", "monitoramento", "levantamento"],
    keywords: ["levantamento fauna", "monitoramento fauna", "salvamento fauna", "resgate fauna", "destinacao fauna"],
    summary: "Estabelece critérios para procedimentos relacionados a levantamento, monitoramento, salvamento, resgate e destinação de fauna silvestre no contexto de empreendimentos e atividades.",
    relevance: "É uma das referências federais diretamente relacionadas a estudos e salvamento de fauna.",
    url: "https://www.ibama.gov.br/component/legislacao/?view=legislacao&legislacao=113065",
    verified: "out/2026"
  },
  {
    id: "in-ibama-8-2017",
    title: "IN Ibama nº 8/2017 — Abio",
    scope: "Federal",
    uf: "BR",
    authority: "Ibama",
    themes: ["fauna", "resgate", "afugentamento", "salvamento", "monitoramento", "levantamento", "captura"],
    keywords: ["abio", "captura", "coleta", "transporte material biologico", "afugentamento", "resgate", "levantamento fauna", "monitoramento fauna"],
    summary: "Disciplina a Autorização para Captura, Coleta e Transporte de Material Biológico no licenciamento ambiental federal e define conceitos relacionados a afugentamento, resgate, monitoramento, levantamento e soltura.",
    relevance: "É especialmente relevante quando o manejo de fauna está inserido em processo de licenciamento ambiental federal.",
    url: "https://www.ibama.gov.br/component/legislacao/?view=legislacao&legislacao=137264",
    verified: "out/2026"
  },
  {
    id: "cfbio-706-2024",
    title: "Resolução CFBio nº 706/2024",
    scope: "Federal",
    uf: "BR",
    authority: "Conselho Federal de Biologia",
    themes: ["fauna", "profissional", "manejo", "captura", "soltura"],
    keywords: ["biologo", "biólogo", "fauna", "captura", "contencao", "marcacao", "soltura", "vertebrados"],
    summary: "Padroniza procedimentos de estudo, registro, captura, contenção, marcação, soltura e coleta de animais vertebrados na atuação do Biólogo, com princípios de biossegurança e bem-estar.",
    relevance: "É uma referência profissional quando o serviço envolve procedimentos com fauna vertebrada realizados por Biólogos.",
    url: "https://cfbio.gov.br/2024/07/10/resolucao-no-706-de-22-de-junho-de-2024/",
    verified: "out/2026"
  },
  {
    id: "mma-1704-2026",
    title: "Portaria MMA nº 1.704/2026 — Fauna Ameaçada",
    scope: "Federal",
    uf: "BR",
    authority: "MMA / ICMBio",
    themes: ["fauna", "ameacadas", "levantamento", "monitoramento"],
    keywords: ["especies ameacadas", "extincao", "aves", "anfibios", "repteis", "mamiferos", "invertebrados terrestres"],
    summary: "Atualiza a Lista Nacional Oficial de Espécies da Fauna Ameaçadas de Extinção para invertebrados terrestres, aves, anfíbios, répteis e mamíferos.",
    relevance: "É referência para análise do status de conservação dos registros faunísticos.",
    url: "https://www.gov.br/icmbio/pt-br/assuntos/biodiversidade/fauna-brasileira/portarias-fauna-ameacada",
    verified: "out/2026"
  },
  {
    id: "mma-1667-2026",
    title: "Portaria MMA nº 1.667/2026 — Fauna Aquática Ameaçada",
    scope: "Federal",
    uf: "BR",
    authority: "MMA / ICMBio",
    themes: ["fauna", "ameacadas", "levantamento", "monitoramento", "aquaticos"],
    keywords: ["peixes", "invertebrados aquaticos", "especies ameacadas", "extincao", "fauna aquatica"],
    summary: "Atualiza a Lista Nacional Oficial de Espécies da Fauna Ameaçadas de Extinção para peixes e invertebrados aquáticos.",
    relevance: "Deve ser considerada quando o levantamento ou monitoramento incluir fauna aquática.",
    url: "https://www.gov.br/icmbio/pt-br/assuntos/biodiversidade/fauna-brasileira/portarias-fauna-ameacada",
    verified: "out/2026"
  },
  {
    id: "conama-01-1990",
    title: "Resolução CONAMA nº 01/1990 — Emissão de Ruídos",
    scope: "Federal",
    uf: "BR",
    authority: "CONAMA / Ibama",
    themes: ["ruido", "qualidade ambiental", "monitoramento"],
    keywords: ["ruido", "ruído", "poluicao sonora", "pressao sonora", "monitoramento de ruido", "niveis de ruido", "nbr 10151"],
    summary: "Estabelece critérios de referência para emissão de ruídos decorrentes de atividades e remete à norma técnica aplicável à avaliação do ruído em áreas habitadas.",
    relevance: "É uma referência federal para avaliações de ruído ambiental associadas a atividades industriais, comerciais, sociais ou recreativas.",
    url: "https://www.gov.br/ibama/pt-br/assuntos/emissoes-e-residuos/emissoes/programa-silencio",
    verified: "out/2026"
  },
  {
    id: "conama-02-1990",
    title: "Resolução CONAMA nº 02/1990 — Programa Silêncio",
    scope: "Federal",
    uf: "BR",
    authority: "CONAMA / Ibama",
    themes: ["ruido", "qualidade ambiental", "educacao ambiental"],
    keywords: ["programa silencio", "ruido", "ruído", "poluicao sonora", "educacao controle ruido"],
    summary: "Institui o Programa Nacional de Educação e Controle da Poluição Sonora — Programa Silêncio, coordenado pelo Ibama.",
    relevance: "Complementa a referência federal sobre controle da poluição sonora e organização de ações de educação e controle de ruído.",
    url: "https://www.gov.br/ibama/pt-br/assuntos/emissoes-e-residuos/emissoes/programa-silencio",
    verified: "out/2026"
  },
  {
    id: "anac-rbac-100-2026",
    title: "RBAC nº 100/2026 — Aeronaves Não Tripuladas",
    scope: "Federal",
    uf: "BR",
    authority: "ANAC",
    themes: ["geotecnologia", "drone", "aeronave nao tripulada"],
    keywords: ["drone", "drones", "uas", "aeronave nao tripulada", "mapeamento aereo", "voo"],
    summary: "Estabelece requisitos gerais para aeronaves não tripuladas de uso civil e organiza as categorias e condições de operação aplicáveis.",
    relevance: "É referência regulatória federal para operações profissionais com drones realizadas no Brasil.",
    url: "https://www.anac.gov.br/assuntos/legislacao/legislacao-1/boletim-de-pessoal/2026/bps-v-21-no-24-15-a-19-06-2026/rbac-100-emd-00/visualizar_ato_normativo",
    verified: "out/2026"
  },
  {
    id: "decea-ica-100-40-2026",
    title: "ICA 100-40/2026 — Acesso ao Espaço Aéreo por Aeronaves Não Tripuladas",
    scope: "Federal",
    uf: "BR",
    authority: "DECEA",
    themes: ["geotecnologia", "drone", "espaco aereo"],
    keywords: ["drone", "drones", "sarpas", "espaco aereo", "aeronave nao tripulada", "autorizacao voo"],
    summary: "Estabelece procedimentos e responsabilidades para o acesso seguro ao Espaço Aéreo Brasileiro por aeronaves não tripuladas.",
    relevance: "É referência operacional para planejamento e solicitação de acesso ao espaço aéreo em voos com drones.",
    url: "https://publicacoes.decea.mil.br/publicacao/ica-100-40",
    verified: "out/2026"
  },
  {
    id: "ba-inema-tr-inventario-florestal",
    title: "INEMA — Termo de Referência para Inventário Florestal",
    scope: "Estadual",
    uf: "BA",
    authority: "INEMA",
    themes: ["flora", "inventario florestal", "supressao"],
    keywords: ["bahia", "inventario florestal", "asv", "supressao vegetacao", "amostragem", "volume florestal"],
    summary: "Referência técnica disponibilizada pelo INEMA para orientar a elaboração de inventários florestais em processos administrativos florestais, com critérios conforme a finalidade do levantamento.",
    relevance: "É uma referência direta para inventários vinculados a processos florestais estaduais na Bahia.",
    url: "https://www.ba.gov.br/inema/sites/site-inema/files/migracao_2024/arquivos/wp-content/files/IN-ATD-002-00_Termo_de_Referncia_para_a_Elaborao_de_Inventrio_Florestal.pdf",
    verified: "out/2026"
  },

  {
    id: "ba-12056-2011",
    title: "Lei Estadual nº 12.056/2011 — Política de Educação Ambiental da Bahia",
    scope: "Estadual",
    uf: "BA",
    authority: "Estado da Bahia",
    themes: ["educacao ambiental", "licenciamento", "socioambiental"],
    keywords: ["bahia", "educacao ambiental", "programa educacao ambiental", "pea", "treinamento", "oficina", "comunidade"],
    summary: "Institui a Política de Educação Ambiental do Estado da Bahia e estabelece princípios, objetivos, diretrizes e instrumentos para ações de educação ambiental.",
    relevance: "É a principal referência estadual cadastrada nesta base para programas e ações de educação ambiental na Bahia.",
    url: "https://www.ba.gov.br/meioambiente/sites/site-sema/files/migracao_2024/arquivos/File/Publicacoes/Livros/PoliticaEducacaoAmbiental.pdf",
    verified: "out/2026"
  },
  {
    id: "ba-decreto-19083-2019",
    title: "Decreto Estadual nº 19.083/2019 — Educação Ambiental",
    scope: "Estadual",
    uf: "BA",
    authority: "Estado da Bahia",
    themes: ["educacao ambiental", "licenciamento", "socioambiental"],
    keywords: ["bahia", "educacao ambiental", "pea", "programa estadual", "licenciamento ambiental", "socioambiental"],
    summary: "Regulamenta a Lei Estadual nº 12.056/2011 e disciplina instrumentos da Política Estadual de Educação Ambiental da Bahia.",
    relevance: "Complementa a política estadual e orienta a implementação de seus instrumentos no território baiano.",
    url: "https://www.ba.gov.br/meioambiente/sites/site-sema/files/migracao_2024/arquivos/File/Ascom/00Decreto_EA.pdf",
    verified: "out/2026"
  },
  {
    id: "ba-11612-2009",
    title: "Lei Estadual nº 11.612/2009 — Política Estadual de Recursos Hídricos",
    scope: "Estadual",
    uf: "BA",
    authority: "Estado da Bahia",
    themes: ["recursos_hidricos", "outorga", "agua", "licenciamento"],
    keywords: ["bahia", "recursos hidricos", "agua", "outorga", "captacao", "lancamento", "barramento", "poco", "irrigacao"],
    summary: "Institui a Política Estadual de Recursos Hídricos e o Sistema Estadual de Gerenciamento de Recursos Hídricos da Bahia, estruturando instrumentos de gestão como planejamento, outorga, cadastro, monitoramento e demais mecanismos previstos na política estadual.",
    relevance: "É uma referência central para demandas que envolvam uso de águas superficiais ou subterrâneas, intervenções em corpos hídricos e regularização de usos da água na Bahia.",
    url: "https://www.ba.gov.br/meioambiente/220/legislacao-ferhba",
    verified: "out/2026"
  },
  {
    id: "ba-inema-22078-2021",
    title: "Portaria INEMA nº 22.078/2021 — Reserva Legal",
    scope: "Estadual",
    uf: "BA",
    authority: "INEMA",
    themes: ["rural", "reserva legal", "flora", "regularizacao"],
    keywords: ["bahia", "reserva legal", "rl", "imovel rural", "cefir", "realocacao", "compensacao"],
    summary: "Estabelece procedimentos e critérios para aprovação da localização da Reserva Legal no Estado da Bahia. O texto consolidado disponibilizado pelo INEMA registra alteração pela Portaria INEMA nº 27.646/2022.",
    relevance: "É relevante para imóveis rurais que precisem cadastrar, aprovar, realocar ou tratar situações relacionadas à Reserva Legal no âmbito estadual.",
    url: "https://www.ba.gov.br/inema/sites/site-inema/files/migracao_2024/arquivos/wp-content/files/PORTARIA_RL_alterao_consolidada_formatada_para_site.pdf",
    verified: "out/2026"
  },
  {
    id: "ba-cefir-car",
    title: "INEMA — CAR Bahia / CEFIR",
    scope: "Estadual",
    uf: "BA",
    authority: "INEMA",
    themes: ["rural", "cefir", "car", "reserva legal", "regularizacao"],
    keywords: ["bahia", "cefir", "car", "cadastro ambiental rural", "imovel rural", "reserva legal", "app", "regularizacao ambiental"],
    summary: "Na Bahia, o Cadastro Ambiental Rural é implementado por meio do Cadastro Estadual Florestal de Imóveis Rurais — CEFIR. O INEMA informa que o cadastro integra informações ambientais do imóvel rural e se relaciona a autorizações e procedimentos ambientais estaduais.",
    relevance: "É uma referência prática para proprietários e possuidores rurais que precisam entender cadastro ambiental, APP, Reserva Legal e regularização do imóvel na Bahia.",
    url: "https://www.ba.gov.br/inema/iniciativas/car-bahia-cefir",
    verified: "out/2026"
  },
  {
    id: "ba-inema-in-002-2021",
    title: "IN INEMA nº 002/2021 — Desativação e Reabilitação de Áreas",
    scope: "Estadual",
    uf: "BA",
    authority: "INEMA",
    themes: ["recuperacao", "licenciamento", "area degradada", "desativacao"],
    keywords: ["bahia", "desativacao empreendimento", "encerramento atividade", "reabilitacao area", "remediacao", "area contaminada", "prad"],
    summary: "Estabelece procedimentos para desativação total ou parcial de empreendimentos potencialmente poluidores, encerramento de atividades e reabilitação de áreas no contexto do licenciamento ambiental.",
    relevance: "Pode ser relevante em encerramento de operações, descomissionamento, áreas contaminadas e demandas de recuperação ou reabilitação ambiental.",
    url: "https://www.ba.gov.br/inema/sites/site-inema/files/migracao_2024/arquivos/wp-content/files/INEMA_-_Instrucao_Normativa_002_-_Desativaco_Total_ou_Parcial_de_Empreendimentos_potencialmente_poluidores_-_Desativao_de_Plantas.pdf",
    verified: "out/2026"
  },
  {
    id: "ba-10431-2006",
    title: "Lei Estadual nº 10.431/2006 — Bahia",
    scope: "Estadual",
    uf: "BA",
    authority: "Estado da Bahia",
    themes: ["licenciamento", "fauna", "flora", "supressao", "biodiversidade"],
    keywords: ["bahia", "licenciamento", "supressao vegetacao", "fauna", "flora", "biodiversidade"],
    summary: "Institui a Política de Meio Ambiente e de Proteção à Biodiversidade do Estado da Bahia e integra a base estadual para licenciamento, proteção da fauna, flora e demais recursos ambientais.",
    relevance: "É uma referência central para consultas ambientais vinculadas ao licenciamento estadual da Bahia.",
    url: "https://www.ba.gov.br/meioambiente/sites/site-sema/files/migracao_2024/arquivos/File/Legislacao/Leis/lei10431.pdf",
    verified: "out/2026"
  },
  {
    id: "ba-14024-2012",
    title: "Decreto Estadual nº 14.024/2012 — Bahia",
    scope: "Estadual",
    uf: "BA",
    authority: "Estado da Bahia",
    themes: ["licenciamento", "fauna", "flora", "supressao"],
    keywords: ["bahia", "licenciamento", "autorizacao", "vegetacao", "fauna", "flora"],
    summary: "Regulamenta a Política Estadual de Meio Ambiente e disciplina procedimentos relacionados ao licenciamento e às autorizações ambientais no Estado da Bahia.",
    relevance: "Complementa a Lei Estadual nº 10.431/2006 na análise de procedimentos ambientais estaduais.",
    url: "https://www.ba.gov.br/meioambiente/sites/site-sema/files/migracao_2024/arquivos/File/FERFA/Legislacao/novo14024.pdf",
    verified: "out/2026"
  },
  {
    id: "ba-inema-001-2016",
    title: "IN INEMA nº 001/2016 — Manejo de Fauna na Bahia",
    scope: "Estadual",
    uf: "BA",
    authority: "INEMA",
    themes: ["fauna", "resgate", "afugentamento", "salvamento", "monitoramento", "levantamento", "soltura"],
    keywords: ["bahia", "resgate fauna", "afugentamento fauna", "salvamento fauna", "amf", "levantamento fauna", "monitoramento fauna", "soltura"],
    summary: "Estabelece diretrizes, critérios e procedimentos para a Autorização para Manejo de Fauna Silvestre no licenciamento ambiental estadual da Bahia.",
    relevance: "É a principal referência estadual cadastrada nesta base para levantamento, salvamento, afugentamento, resgate, monitoramento e soltura de fauna no licenciamento do INEMA.",
    url: "https://www.ba.gov.br/inema/sites/site-inema/files/migracao_2024/arquivos/wp-content/files/IN_INEMA_n001_2016_-_AMF.pdf",
    verified: "out/2026"
  },
  {
    id: "ba-inema-22129-2021",
    title: "Portaria INEMA nº 22.129/2021 — Destinação de Fauna",
    scope: "Estadual",
    uf: "BA",
    authority: "INEMA",
    themes: ["fauna", "resgate", "soltura", "destinacao", "asas"],
    keywords: ["bahia", "areas de soltura", "asas", "destinacao animais", "resgate fauna", "soltura fauna"],
    summary: "Regulamenta a destinação de animais silvestres e o cadastro de Áreas de Soltura de Animais Silvestres no Estado da Bahia.",
    relevance: "É importante quando a dúvida envolve destinação ou soltura de animais resgatados.",
    url: "https://www.ba.gov.br/inema/sites/site-inema/files/migracao_2024/arquivos/wp-content/files/Portaria_22129-2021_Destinao_Fauna_Silvestre.pdf",
    verified: "out/2026"
  },
  {
    id: "ba-sema-37-2017",
    title: "Portaria SEMA nº 37/2017 — Fauna Ameaçada da Bahia",
    scope: "Estadual",
    uf: "BA",
    authority: "SEMA Bahia",
    themes: ["fauna", "ameacadas", "levantamento", "monitoramento"],
    keywords: ["bahia", "especies ameacadas", "fauna ameacada", "extincao", "levantamento fauna"],
    summary: "Torna pública a Lista Oficial das Espécies da Fauna Ameaçadas de Extinção do Estado da Bahia.",
    relevance: "É referência estadual para identificar espécies ameaçadas registradas em levantamentos e monitoramentos na Bahia.",
    url: "https://gestor.meioambiente.ba.gov.br/Consultas/ConsultaPublicacao/index.php?PaginaMostrada=28&alt=0&ano=&classificacao=&colegiado=&dt_publicacao_inicio=&dt_publicacao_termino=&num_processo=&numero=&order=4&texto=&tipoPublicacao=22&typeOrder=0",
    verified: "out/2026"
  },
  {
    id: "ba-sema-40-2017",
    title: "Portaria SEMA nº 40/2017 — Flora Ameaçada da Bahia",
    scope: "Estadual",
    uf: "BA",
    authority: "SEMA Bahia",
    themes: ["flora", "ameacadas", "supressao", "biodiversidade"],
    keywords: ["bahia", "flora ameacada", "especies ameacadas", "especies endemicas", "extincao", "supressao vegetal", "inventario florestal"],
    summary: "Torna pública a lista estadual de espécies endêmicas da flora ameaçadas de extinção na Bahia e constitui referência para análise de registros florísticos e intervenções em vegetação.",
    relevance: "É uma referência estadual importante para inventários, levantamentos florísticos e avaliação de áreas sujeitas a intervenção ou supressão vegetal.",
    url: "https://www.ba.gov.br/meioambiente/284/lista-de-especies-ameacadas-de-extincao",
    verified: "out/2026"
  },
  {
    id: "ba-sema-supressao",
    title: "SEMA Bahia — Orientação sobre Supressão de Vegetação Nativa",
    scope: "Estadual",
    uf: "BA",
    authority: "SEMA Bahia",
    themes: ["flora", "supressao", "vegetacao", "autorizacao"],
    keywords: ["bahia", "supressao vegetacao", "cortar arvores", "retirar arvores", "terreno", "asv"],
    summary: "Página institucional da SEMA Bahia informa que a supressão de vegetação nativa depende de autorização do órgão competente e direciona para os procedimentos administrativos aplicáveis.",
    relevance: "É uma referência prática inicial para dúvidas sobre retirada de vegetação nativa na Bahia.",
    url: "https://www.ba.gov.br/meioambiente/117/supressao-de-vegetacao-nativa",
    verified: "out/2026"
  }
];
