window.JSB_LEGAL_DATABASE = [
  {
    id: "cf-225",
    title: "Constituição Federal — art. 225",
    scope: "Federal",
    uf: "BR",
    authority: "Presidência da República",
    themes: ["licenciamento", "fauna", "flora", "supressao", "biodiversidade"],
    keywords: ["meio ambiente", "fauna", "flora", "degradacao", "impacto ambiental", "estudo previo"],
    summary: "Estabelece o direito ao meio ambiente ecologicamente equilibrado e impõe ao Poder Público e à coletividade o dever de defendê-lo e preservá-lo, incluindo proteção da fauna e flora e exigência de estudo prévio de impacto ambiental para atividades potencialmente causadoras de significativa degradação.",
    relevance: "É a base constitucional para proteção ambiental, licenciamento, fauna, flora e avaliação de impactos.",
    url: "https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm",
    verified: "out/2026"
  },
  {
    id: "lei-5197-1967",
    title: "Lei nº 5.197/1967 — Proteção à Fauna",
    scope: "Federal",
    uf: "BR",
    authority: "Presidência da República",
    themes: ["fauna", "resgate", "manejo", "captura", "salvamento"],
    keywords: ["fauna silvestre", "captura", "apanha", "perseguicao", "animais silvestres"],
    summary: "Dispõe sobre a proteção da fauna silvestre e estabelece regras gerais para utilização, perseguição, destruição, caça ou apanha de animais silvestres.",
    relevance: "É uma das referências federais centrais para atividades que envolvam manejo de fauna silvestre.",
    url: "https://www.planalto.gov.br/ccivil_03/leis/l5197compilado.htm",
    verified: "out/2026"
  },
  {
    id: "lei-6938-1981",
    title: "Lei nº 6.938/1981 — Política Nacional do Meio Ambiente",
    scope: "Federal",
    uf: "BR",
    authority: "Presidência da República",
    themes: ["licenciamento", "impacto", "gestao ambiental"],
    keywords: ["politica nacional meio ambiente", "sisnama", "licenciamento", "poluidor", "degradacao"],
    summary: "Institui a Política Nacional do Meio Ambiente, estrutura o Sisnama e estabelece instrumentos de gestão ambiental, entre eles o licenciamento.",
    relevance: "Ajuda a contextualizar o licenciamento e a atuação dos órgãos ambientais.",
    url: "https://www.planalto.gov.br/ccivil_03/leis/l6938compilada.htm",
    verified: "out/2026"
  },
  {
    id: "lei-9605-1998",
    title: "Lei nº 9.605/1998 — Lei de Crimes Ambientais",
    scope: "Federal",
    uf: "BR",
    authority: "Presidência da República",
    themes: ["fauna", "flora", "supressao", "responsabilidade"],
    keywords: ["crime ambiental", "fauna", "flora", "corte arvore", "captura", "autorizacao"],
    summary: "Dispõe sobre sanções penais e administrativas derivadas de condutas e atividades lesivas ao meio ambiente, incluindo condutas contra a fauna e a flora.",
    relevance: "É relevante quando a atividade pode depender de autorização ambiental ou envolver fauna e vegetação protegidas.",
    url: "https://www.planalto.gov.br/ccivil_03/leis/l9605.htm",
    verified: "out/2026"
  },
  {
    id: "decreto-6514-2008",
    title: "Decreto nº 6.514/2008 — Infrações e Sanções Administrativas Ambientais",
    scope: "Federal",
    uf: "BR",
    authority: "Presidência da República",
    themes: ["fauna", "flora", "supressao", "responsabilidade"],
    keywords: ["infracao ambiental", "multa", "fauna", "flora", "desmatamento", "supressao"],
    summary: "Regulamenta infrações e sanções administrativas ambientais federais e trata de condutas relacionadas à fauna, flora e outras formas de degradação ambiental.",
    relevance: "Ajuda a identificar consequências administrativas de intervenções ambientais executadas em desacordo com a legislação.",
    url: "https://www.planalto.gov.br/ccivil_03/_ato2007-2010/2008/decreto/d6514.htm",
    verified: "out/2026"
  },
  {
    id: "lc-140-2011",
    title: "Lei Complementar nº 140/2011",
    scope: "Federal",
    uf: "BR",
    authority: "Presidência da República",
    themes: ["competencia", "licenciamento", "fauna", "flora", "supressao"],
    keywords: ["competencia", "uniao", "estado", "municipio", "licenciamento", "autorizacao ambiental"],
    summary: "Organiza a cooperação administrativa entre União, Estados, Distrito Federal e Municípios nas ações de proteção ambiental e ajuda a definir qual ente atua no licenciamento e em autorizações ambientais.",
    relevance: "É fundamental para entender por que a localização do empreendimento, sozinha, não define qual órgão será competente.",
    url: "https://www.planalto.gov.br/ccivil_03/leis/lcp/lcp140.htm",
    verified: "out/2026"
  },
  {
    id: "lei-12651-2012",
    title: "Lei nº 12.651/2012 — Proteção da Vegetação Nativa",
    scope: "Federal",
    uf: "BR",
    authority: "Presidência da República",
    themes: ["flora", "supressao", "vegetacao", "app", "reserva legal"],
    keywords: ["arvore", "arvores", "vegetacao nativa", "supressao vegetal", "app", "reserva legal", "imovel rural"],
    summary: "Dispõe sobre a proteção da vegetação nativa e estabelece regras relacionadas a Áreas de Preservação Permanente, Reserva Legal e intervenções em vegetação.",
    relevance: "É uma referência importante quando a dúvida envolve corte ou supressão de vegetação nativa, especialmente em APP, Reserva Legal ou imóvel rural.",
    url: "https://www.planalto.gov.br/ccivil_03/_ato2011-2014/2012/lei/l12651.htm",
    verified: "out/2026"
  },
  {
    id: "lei-11428-2006",
    title: "Lei nº 11.428/2006 — Lei da Mata Atlântica",
    scope: "Federal",
    uf: "BR",
    authority: "Presidência da República",
    themes: ["flora", "supressao", "vegetacao", "mata atlantica"],
    keywords: ["mata atlantica", "vegetacao", "supressao", "corte", "arvore", "arvores"],
    summary: "Dispõe sobre a utilização e proteção da vegetação nativa do Bioma Mata Atlântica e estabelece regras específicas para supressão e intervenção quando o bioma for aplicável.",
    relevance: "Pode ser determinante em terrenos inseridos no Bioma Mata Atlântica ou em formações vegetais abrangidas pela lei.",
    url: "https://www.planalto.gov.br/ccivil_03/_ato2004-2006/2006/lei/l11428.htm",
    verified: "out/2026"
  },
  {
    id: "lei-15190-2025",
    title: "Lei nº 15.190/2025 — Lei Geral do Licenciamento Ambiental",
    scope: "Federal",
    uf: "BR",
    authority: "Presidência da República",
    themes: ["licenciamento", "empreendimento", "estudos ambientais"],
    keywords: ["licenciamento ambiental", "obra", "empreendimento", "farmacia", "construcao", "estudo ambiental"],
    summary: "Estabelece normas gerais para o licenciamento ambiental no Brasil e disciplina modalidades, estudos, procedimentos e responsabilidades aplicáveis ao processo.",
    relevance: "É uma referência geral para dúvidas sobre implantação de empreendimentos e necessidade de licenciamento ambiental.",
    url: "https://www.planalto.gov.br/ccivil_03/_ato2023-2026/2025/lei/l15190.htm",
    verified: "out/2026"
  },
  {
    id: "in-ibama-146-2007",
    title: "IN Ibama nº 146/2007",
    scope: "Federal",
    uf: "BR",
    authority: "Ibama",
    themes: ["fauna", "resgate", "salvamento", "monitoramento", "levantamento"],
    keywords: ["levantamento fauna", "monitoramento fauna", "salvamento fauna", "resgate fauna", "destinacao fauna"],
    summary: "Estabelece critérios para procedimentos relacionados a levantamento, monitoramento, salvamento, resgate e destinação de fauna silvestre no contexto de empreendimentos e atividades.",
    relevance: "É uma das referências federais diretamente relacionadas a estudos e salvamento de fauna.",
    url: "https://www.ibama.gov.br/component/legislacao/?view=legislacao&legislacao=113065",
    verified: "out/2026"
  },
  {
    id: "in-ibama-141-2006",
    title: "IN Ibama nº 141/2006 — Fauna Sinantrópica Nociva",
    scope: "Federal",
    uf: "BR",
    authority: "Ibama",
    themes: ["fauna", "exoticas", "sinantropica", "abelhas", "controle"],
    keywords: ["fauna sinantropica", "fauna sinantrópica", "abelhas", "apis mellifera", "abelha africana", "abelha africanizada", "especie exotica", "espécie exótica", "controle fauna", "remocao enxame", "remoção enxame"],
    summary: "Regulamenta o controle e o manejo ambiental da fauna sinantrópica nociva. A norma inclui abelhas entre os artrópodes nocivos que, quando enquadrados como fauna sinantrópica nociva e observadas as demais regras aplicáveis, podem ser controlados por pessoas físicas ou jurídicas devidamente habilitadas sem autorização específica do Ibama.",
    relevance: "É referência importante para ocorrências de abelhas em ambiente antrópico quando houver risco, transtorno significativo ou necessidade de controle. A simples identificação de uma abelha como exótica não significa, por si só, que qualquer método de remoção ou eliminação esteja automaticamente autorizado.",
    url: "https://www.ibama.gov.br/component/legislacao/?legislacao=112966&view=legislacao",
    verified: "out/2026"
  },
  {
    id: "in-ibama-8-2017",
    title: "IN Ibama nº 8/2017 — Abio",
    scope: "Federal",
    uf: "BR",
    authority: "Ibama",
    themes: ["fauna", "resgate", "afugentamento", "salvamento", "monitoramento", "levantamento", "captura"],
    keywords: ["abio", "captura", "coleta", "transporte material biologico", "afugentamento", "resgate", "levantamento fauna", "monitoramento fauna"],
    summary: "Disciplina a Autorização para Captura, Coleta e Transporte de Material Biológico no licenciamento ambiental federal e define conceitos relacionados a afugentamento, resgate, monitoramento, levantamento e soltura.",
    relevance: "É especialmente relevante quando o manejo de fauna está inserido em processo de licenciamento ambiental federal.",
    url: "https://www.ibama.gov.br/component/legislacao/?view=legislacao&legislacao=137264",
    verified: "out/2026"
  },
  {
    id: "cfbio-706-2024",
    title: "Resolução CFBio nº 706/2024",
    scope: "Federal",
    uf: "BR",
    authority: "Conselho Federal de Biologia",
    themes: ["fauna", "profissional", "manejo", "captura", "soltura"],
    keywords: ["biologo", "biólogo", "fauna", "captura", "contencao", "marcacao", "soltura", "vertebrados"],
    summary: "Padroniza procedimentos de estudo, registro, captura, contenção, marcação, soltura e coleta de animais vertebrados na atuação do Biólogo, com princípios de biossegurança e bem-estar.",
    relevance: "É uma referência profissional quando o serviço envolve procedimentos com fauna vertebrada realizados por Biólogos.",
    url: "https://cfbio.gov.br/2024/07/10/resolucao-no-706-de-22-de-junho-de-2024/",
    verified: "out/2026"
  },
  {
    id: "mma-1704-2026",
    title: "Portaria MMA nº 1.704/2026 — Fauna Ameaçada",
    scope: "Federal",
    uf: "BR",
    authority: "MMA / ICMBio",
    themes: ["fauna", "ameacadas", "levantamento", "monitoramento"],
    keywords: ["especies ameacadas", "extincao", "aves", "anfibios", "repteis", "mamiferos", "invertebrados terrestres"],
    summary: "Atualiza a Lista Nacional Oficial de Espécies da Fauna Ameaçadas de Extinção para invertebrados terrestres, aves, anfíbios, répteis e mamíferos.",
    relevance: "É referência para análise do status de conservação dos registros faunísticos.",
    url: "https://www.gov.br/icmbio/pt-br/assuntos/biodiversidade/fauna-brasileira/portarias-fauna-ameacada",
    verified: "out/2026"
  },
  {
    id: "mma-1667-2026",
    title: "Portaria MMA nº 1.667/2026 — Fauna Aquática Ameaçada",
    scope: "Federal",
    uf: "BR",
    authority: "MMA / ICMBio",
    themes: ["fauna", "ameacadas", "levantamento", "monitoramento", "aquaticos"],
    keywords: ["peixes", "invertebrados aquaticos", "especies ameacadas", "extincao", "fauna aquatica"],
    summary: "Atualiza a Lista Nacional Oficial de Espécies da Fauna Ameaçadas de Extinção para peixes e invertebrados aquáticos.",
    relevance: "Deve ser considerada quando o levantamento ou monitoramento incluir fauna aquática.",
    url: "https://www.gov.br/icmbio/pt-br/assuntos/biodiversidade/fauna-brasileira/portarias-fauna-ameacada",
    verified: "out/2026"
  },
  {
    id: "conama-01-1990",
    title: "Resolução CONAMA nº 01/1990 — Emissão de Ruídos",
    scope: "Federal",
    uf: "BR",
    authority: "CONAMA / Ibama",
    themes: ["ruido", "qualidade ambiental", "monitoramento"],
    keywords: ["ruido", "ruído", "poluicao sonora", "pressao sonora", "monitoramento de ruido", "niveis de ruido", "nbr 10151"],
    summary: "Estabelece critérios de referência para emissão de ruídos decorrentes de atividades e remete à norma técnica aplicável à avaliação do ruído em áreas habitadas.",
    relevance: "É uma referência federal para avaliações de ruído ambiental associadas a atividades industriais, comerciais, sociais ou recreativas.",
    url: "https://www.gov.br/ibama/pt-br/assuntos/emissoes-e-residuos/emissoes/programa-silencio",
    verified: "out/2026"
  },
  {
    id: "conama-02-1990",
    title: "Resolução CONAMA nº 02/1990 — Programa Silêncio",
    scope: "Federal",
    uf: "BR",
    authority: "CONAMA / Ibama",
    themes: ["ruido", "qualidade ambiental", "educacao ambiental"],
    keywords: ["programa silencio", "ruido", "ruído", "poluicao sonora", "educacao controle ruido"],
    summary: "Institui o Programa Nacional de Educação e Controle da Poluição Sonora — Programa Silêncio, coordenado pelo Ibama.",
    relevance: "Complementa a referência federal sobre controle da poluição sonora e organização de ações de educação e controle de ruído.",
    url: "https://www.gov.br/ibama/pt-br/assuntos/emissoes-e-residuos/emissoes/programa-silencio",
    verified: "out/2026"
  },
  {
    id: "anac-rbac-100-2026",
    title: "RBAC nº 100/2026 — Aeronaves Não Tripuladas",
    scope: "Federal",
    uf: "BR",
    authority: "ANAC",
    themes: ["geotecnologia", "drone", "aeronave nao tripulada"],
    keywords: ["drone", "drones", "uas", "aeronave nao tripulada", "mapeamento aereo", "voo"],
    summary: "Estabelece requisitos gerais para aeronaves não tripuladas de uso civil e organiza as categorias e condições de operação aplicáveis.",
    relevance: "É referência regulatória federal para operações profissionais com drones realizadas no Brasil.",
    url: "https://www.anac.gov.br/assuntos/legislacao/legislacao-1/boletim-de-pessoal/2026/bps-v-21-no-24-15-a-19-06-2026/rbac-100-emd-00/visualizar_ato_normativo",
    verified: "out/2026"
  },
  {
    id: "decea-ica-100-40-2026",
    title: "ICA 100-40/2026 — Acesso ao Espaço Aéreo por Aeronaves Não Tripuladas",
    scope: "Federal",
    uf: "BR",
    authority: "DECEA",
    themes: ["geotecnologia", "drone", "espaco aereo"],
    keywords: ["drone", "drones", "sarpas", "espaco aereo", "aeronave nao tripulada", "autorizacao voo"],
    summary: "Estabelece procedimentos e responsabilidades para o acesso seguro ao Espaço Aéreo Brasileiro por aeronaves não tripuladas.",
    relevance: "É referência operacional para planejamento e solicitação de acesso ao espaço aéreo em voos com drones.",
    url: "https://publicacoes.decea.mil.br/publicacao/ica-100-40",
    verified: "out/2026"
  },
  {
    id: "ba-inema-tr-inventario-florestal",
    title: "INEMA — Termo de Referência para Inventário Florestal",
    scope: "Estadual",
    uf: "BA",
    authority: "INEMA",
    themes: ["flora", "inventario florestal", "supressao"],
    keywords: ["bahia", "inventario florestal", "asv", "supressao vegetacao", "amostragem", "volume florestal"],
    summary: "Referência técnica disponibilizada pelo INEMA para orientar a elaboração de inventários florestais em processos administrativos florestais, com critérios conforme a finalidade do levantamento.",
    relevance: "É uma referência direta para inventários vinculados a processos florestais estaduais na Bahia.",
    url: "https://www.ba.gov.br/inema/sites/site-inema/files/migracao_2024/arquivos/wp-content/files/IN-ATD-002-00_Termo_de_Referncia_para_a_Elaborao_de_Inventrio_Florestal.pdf",
    verified: "out/2026"
  },

  {
    id: "ba-12056-2011",
    title: "Lei Estadual nº 12.056/2011 — Política de Educação Ambiental da Bahia",
    scope: "Estadual",
    uf: "BA",
    authority: "Estado da Bahia",
    themes: ["educacao ambiental", "licenciamento", "socioambiental"],
    keywords: ["bahia", "educacao ambiental", "programa educacao ambiental", "pea", "treinamento", "oficina", "comunidade"],
    summary: "Institui a Política de Educação Ambiental do Estado da Bahia e estabelece princípios, objetivos, diretrizes e instrumentos para ações de educação ambiental.",
    relevance: "É a principal referência estadual cadastrada nesta base para programas e ações de educação ambiental na Bahia.",
    url: "https://www.ba.gov.br/meioambiente/sites/site-sema/files/migracao_2024/arquivos/File/Publicacoes/Livros/PoliticaEducacaoAmbiental.pdf",
    verified: "out/2026"
  },
  {
    id: "ba-decreto-19083-2019",
    title: "Decreto Estadual nº 19.083/2019 — Educação Ambiental",
    scope: "Estadual",
    uf: "BA",
    authority: "Estado da Bahia",
    themes: ["educacao ambiental", "licenciamento", "socioambiental"],
    keywords: ["bahia", "educacao ambiental", "pea", "programa estadual", "licenciamento ambiental", "socioambiental"],
    summary: "Regulamenta a Lei Estadual nº 12.056/2011 e disciplina instrumentos da Política Estadual de Educação Ambiental da Bahia.",
    relevance: "Complementa a política estadual e orienta a implementação de seus instrumentos no território baiano.",
    url: "https://www.ba.gov.br/meioambiente/sites/site-sema/files/migracao_2024/arquivos/File/Ascom/00Decreto_EA.pdf",
    verified: "out/2026"
  },
  {
    id: "ba-11612-2009",
    title: "Lei Estadual nº 11.612/2009 — Política Estadual de Recursos Hídricos",
    scope: "Estadual",
    uf: "BA",
    authority: "Estado da Bahia",
    themes: ["recursos_hidricos", "outorga", "agua", "licenciamento"],
    keywords: ["bahia", "recursos hidricos", "agua", "outorga", "captacao", "lancamento", "barramento", "poco", "irrigacao"],
    summary: "Institui a Política Estadual de Recursos Hídricos e o Sistema Estadual de Gerenciamento de Recursos Hídricos da Bahia, estruturando instrumentos de gestão como planejamento, outorga, cadastro, monitoramento e demais mecanismos previstos na política estadual.",
    relevance: "É uma referência central para demandas que envolvam uso de águas superficiais ou subterrâneas, intervenções em corpos hídricos e regularização de usos da água na Bahia.",
    url: "https://www.ba.gov.br/meioambiente/220/legislacao-ferhba",
    verified: "out/2026"
  },
  {
    id: "ba-inema-22078-2021",
    title: "Portaria INEMA nº 22.078/2021 — Reserva Legal",
    scope: "Estadual",
    uf: "BA",
    authority: "INEMA",
    themes: ["rural", "reserva legal", "flora", "regularizacao"],
    keywords: ["bahia", "reserva legal", "rl", "imovel rural", "cefir", "realocacao", "compensacao"],
    summary: "Estabelece procedimentos e critérios para aprovação da localização da Reserva Legal no Estado da Bahia. O texto consolidado disponibilizado pelo INEMA registra alteração pela Portaria INEMA nº 27.646/2022.",
    relevance: "É relevante para imóveis rurais que precisem cadastrar, aprovar, realocar ou tratar situações relacionadas à Reserva Legal no âmbito estadual.",
    url: "https://www.ba.gov.br/inema/sites/site-inema/files/migracao_2024/arquivos/wp-content/files/PORTARIA_RL_alterao_consolidada_formatada_para_site.pdf",
    verified: "out/2026"
  },
  {
    id: "ba-cefir-car",
    title: "INEMA — CAR Bahia / CEFIR",
    scope: "Estadual",
    uf: "BA",
    authority: "INEMA",
    themes: ["rural", "cefir", "car", "reserva legal", "regularizacao"],
    keywords: ["bahia", "cefir", "car", "cadastro ambiental rural", "imovel rural", "reserva legal", "app", "regularizacao ambiental"],
    summary: "Na Bahia, o Cadastro Ambiental Rural é implementado por meio do Cadastro Estadual Florestal de Imóveis Rurais — CEFIR. O INEMA informa que o cadastro integra informações ambientais do imóvel rural e se relaciona a autorizações e procedimentos ambientais estaduais.",
    relevance: "É uma referência prática para proprietários e possuidores rurais que precisam entender cadastro ambiental, APP, Reserva Legal e regularização do imóvel na Bahia.",
    url: "https://www.ba.gov.br/inema/iniciativas/car-bahia-cefir",
    verified: "out/2026"
  },
  {
    id: "ba-inema-in-002-2021",
    title: "IN INEMA nº 002/2021 — Desativação e Reabilitação de Áreas",
    scope: "Estadual",
    uf: "BA",
    authority: "INEMA",
    themes: ["recuperacao", "licenciamento", "area degradada", "desativacao"],
    keywords: ["bahia", "desativacao empreendimento", "encerramento atividade", "reabilitacao area", "remediacao", "area contaminada", "prad"],
    summary: "Estabelece procedimentos para desativação total ou parcial de empreendimentos potencialmente poluidores, encerramento de atividades e reabilitação de áreas no contexto do licenciamento ambiental.",
    relevance: "Pode ser relevante em encerramento de operações, descomissionamento, áreas contaminadas e demandas de recuperação ou reabilitação ambiental.",
    url: "https://www.ba.gov.br/inema/sites/site-inema/files/migracao_2024/arquivos/wp-content/files/INEMA_-_Instrucao_Normativa_002_-_Desativaco_Total_ou_Parcial_de_Empreendimentos_potencialmente_poluidores_-_Desativao_de_Plantas.pdf",
    verified: "out/2026"
  },
  {
    id: "ba-10431-2006",
    title: "Lei Estadual nº 10.431/2006 — Bahia",
    scope: "Estadual",
    uf: "BA",
    authority: "Estado da Bahia",
    themes: ["licenciamento", "fauna", "flora", "supressao", "biodiversidade"],
    keywords: ["bahia", "licenciamento", "supressao vegetacao", "fauna", "flora", "biodiversidade"],
    summary: "Institui a Política de Meio Ambiente e de Proteção à Biodiversidade do Estado da Bahia e integra a base estadual para licenciamento, proteção da fauna, flora e demais recursos ambientais.",
    relevance: "É uma referência central para consultas ambientais vinculadas ao licenciamento estadual da Bahia.",
    url: "https://www.ba.gov.br/meioambiente/sites/site-sema/files/migracao_2024/arquivos/File/Legislacao/Leis/lei10431.pdf",
    verified: "out/2026"
  },
  {
    id: "ba-14024-2012",
    title: "Decreto Estadual nº 14.024/2012 — Bahia",
    scope: "Estadual",
    uf: "BA",
    authority: "Estado da Bahia",
    themes: ["licenciamento", "fauna", "flora", "supressao"],
    keywords: ["bahia", "licenciamento", "autorizacao", "vegetacao", "fauna", "flora"],
    summary: "Regulamenta a Política Estadual de Meio Ambiente e disciplina procedimentos relacionados ao licenciamento e às autorizações ambientais no Estado da Bahia.",
    relevance: "Complementa a Lei Estadual nº 10.431/2006 na análise de procedimentos ambientais estaduais.",
    url: "https://www.ba.gov.br/meioambiente/sites/site-sema/files/migracao_2024/arquivos/File/FERFA/Legislacao/novo14024.pdf",
    verified: "out/2026"
  },
  {
    id: "ba-sema-inema-051-2023",
    title: "Portaria Conjunta SEMA/INEMA nº 051/2023 — Espécies Exóticas Invasoras da Bahia",
    scope: "Estadual",
    uf: "BA",
    authority: "SEMA Bahia / INEMA",
    themes: ["fauna", "flora", "exoticas", "invasoras", "abelhas", "controle"],
    keywords: ["bahia", "especies exoticas invasoras", "espécies exóticas invasoras", "apis mellifera", "abelha europeia", "abelha africanizada", "controle especie invasora", "categoria 2", "soltura especie exotica"],
    summary: "Reconhece a Lista Estadual de Espécies Exóticas Invasoras da Bahia e estabelece categorias e regras de prevenção, uso, controle e soltura. A Apis mellifera consta no Anexo 2 como espécie exótica invasora de Categoria 2, isto é, passível de utilização em condições controladas e sujeita à regulamentação específica. A portaria também proíbe a liberação ou soltura na natureza de espécies exóticas invasoras.",
    relevance: "É a principal referência estadual cadastrada para analisar ocorrências de Apis mellifera e outras espécies exóticas invasoras na Bahia. A conduta concreta deve considerar se o enxame está em ambiente antrópico ou natural, se há risco, o objetivo do manejo e as regras específicas aplicáveis.",
    url: "https://www.ba.gov.br/inema/sites/site-inema/files/migracao_2024/arquivos/wp-content/files/PORTARIA_SEMA_INEMA_051_2023_Lista_espcies_exticas_invasoras.pdf",
    verified: "out/2026"
  },
  {
    id: "ba-inema-001-2016",
    title: "IN INEMA nº 001/2016 — Manejo de Fauna na Bahia",
    scope: "Estadual",
    uf: "BA",
    authority: "INEMA",
    themes: ["fauna", "resgate", "afugentamento", "salvamento", "monitoramento", "levantamento", "soltura"],
    keywords: ["bahia", "resgate fauna", "afugentamento fauna", "salvamento fauna", "amf", "levantamento fauna", "monitoramento fauna", "soltura"],
    summary: "Estabelece diretrizes, critérios e procedimentos para a Autorização para Manejo de Fauna Silvestre no licenciamento ambiental estadual da Bahia.",
    relevance: "É a principal referência estadual cadastrada nesta base para levantamento, salvamento, afugentamento, resgate, monitoramento e soltura de fauna no licenciamento do INEMA.",
    url: "https://www.ba.gov.br/inema/sites/site-inema/files/migracao_2024/arquivos/wp-content/files/IN_INEMA_n001_2016_-_AMF.pdf",
    verified: "out/2026"
  },
  {
    id: "ba-inema-22129-2021",
    title: "Portaria INEMA nº 22.129/2021 — Destinação de Fauna",
    scope: "Estadual",
    uf: "BA",
    authority: "INEMA",
    themes: ["fauna", "resgate", "soltura", "destinacao", "asas"],
    keywords: ["bahia", "areas de soltura", "asas", "destinacao animais", "resgate fauna", "soltura fauna"],
    summary: "Regulamenta a destinação de animais silvestres e o cadastro de Áreas de Soltura de Animais Silvestres no Estado da Bahia.",
    relevance: "É importante quando a dúvida envolve destinação ou soltura de animais resgatados.",
    url: "https://www.ba.gov.br/inema/sites/site-inema/files/migracao_2024/arquivos/wp-content/files/Portaria_22129-2021_Destinao_Fauna_Silvestre.pdf",
    verified: "out/2026"
  },
  {
    id: "ba-sema-37-2017",
    title: "Portaria SEMA nº 37/2017 — Fauna Ameaçada da Bahia",
    scope: "Estadual",
    uf: "BA",
    authority: "SEMA Bahia",
    themes: ["fauna", "ameacadas", "levantamento", "monitoramento"],
    keywords: ["bahia", "especies ameacadas", "fauna ameacada", "extincao", "levantamento fauna"],
    summary: "Torna pública a Lista Oficial das Espécies da Fauna Ameaçadas de Extinção do Estado da Bahia.",
    relevance: "É referência estadual para identificar espécies ameaçadas registradas em levantamentos e monitoramentos na Bahia.",
    url: "https://gestor.meioambiente.ba.gov.br/Consultas/ConsultaPublicacao/index.php?PaginaMostrada=28&alt=0&ano=&classificacao=&colegiado=&dt_publicacao_inicio=&dt_publicacao_termino=&num_processo=&numero=&order=4&texto=&tipoPublicacao=22&typeOrder=0",
    verified: "out/2026"
  },
  {
    id: "ba-sema-40-2017",
    title: "Portaria SEMA nº 40/2017 — Flora Ameaçada da Bahia",
    scope: "Estadual",
    uf: "BA",
    authority: "SEMA Bahia",
    themes: ["flora", "ameacadas", "supressao", "biodiversidade"],
    keywords: ["bahia", "flora ameacada", "especies ameacadas", "especies endemicas", "extincao", "supressao vegetal", "inventario florestal"],
    summary: "Torna pública a lista estadual de espécies endêmicas da flora ameaçadas de extinção na Bahia e constitui referência para análise de registros florísticos e intervenções em vegetação.",
    relevance: "É uma referência estadual importante para inventários, levantamentos florísticos e avaliação de áreas sujeitas a intervenção ou supressão vegetal.",
    url: "https://www.ba.gov.br/meioambiente/284/lista-de-especies-ameacadas-de-extincao",
    verified: "out/2026"
  },
  {
    id: "ba-sema-supressao",
    title: "SEMA Bahia — Orientação sobre Supressão de Vegetação Nativa",
    scope: "Estadual",
    uf: "BA",
    authority: "SEMA Bahia",
    themes: ["flora", "supressao", "vegetacao", "autorizacao"],
    keywords: ["bahia", "supressao vegetacao", "cortar arvores", "retirar arvores", "terreno", "asv"],
    summary: "Página institucional da SEMA Bahia informa que a supressão de vegetação nativa depende de autorização do órgão competente e direciona para os procedimentos administrativos aplicáveis.",
    relevance: "É uma referência prática inicial para dúvidas sobre retirada de vegetação nativa na Bahia.",
    url: "https://www.ba.gov.br/meioambiente/117/supressao-de-vegetacao-nativa",
    verified: "out/2026"
  },

  {
    id: "lei-9433-1997",
    title: "Lei nº 9.433/1997 — Política Nacional de Recursos Hídricos",
    scope: "Federal",
    uf: "BR",
    authority: "Presidência da República",
    themes: ["recursos_hidricos", "outorga", "agua", "gestao ambiental"],
    keywords: ["agua", "água", "outorga", "recursos hidricos", "recursos hídricos", "captacao", "captação", "bacia hidrografica", "uso da agua"],
    summary: "Institui a Política Nacional de Recursos Hídricos e o Sistema Nacional de Gerenciamento de Recursos Hídricos, incluindo instrumentos como planos, enquadramento, outorga, cobrança e sistema de informações.",
    relevance: "É a referência federal central para dúvidas sobre uso de águas superficiais ou subterrâneas e outorga, sem substituir as regras do ente competente sobre o corpo hídrico.",
    url: "https://www.planalto.gov.br/ccivil_03/leis/l9433.htm",
    verified: "out/2026"
  },
  {
    id: "lei-9795-1999",
    title: "Lei nº 9.795/1999 — Política Nacional de Educação Ambiental",
    scope: "Federal",
    uf: "BR",
    authority: "Presidência da República",
    themes: ["educacao ambiental", "socioambiental"],
    keywords: ["educacao ambiental", "educação ambiental", "pea", "programa educacao ambiental", "comunidade", "trabalhadores", "sensibilizacao"],
    summary: "Institui a Política Nacional de Educação Ambiental e reconhece a educação ambiental como componente essencial e permanente da educação nacional, em caráter formal e não formal.",
    relevance: "É referência federal para programas, ações e estratégias de educação ambiental, inclusive em contextos de gestão e licenciamento ambiental.",
    url: "https://www.planalto.gov.br/ccivil_03/leis/l9795.htm",
    verified: "out/2026"
  },
  {
    id: "lei-9985-2000",
    title: "Lei nº 9.985/2000 — Sistema Nacional de Unidades de Conservação",
    scope: "Federal",
    uf: "BR",
    authority: "Presidência da República",
    themes: ["unidades_conservacao", "biodiversidade", "licenciamento", "fauna", "flora"],
    keywords: ["snuc", "unidade de conservacao", "unidade de conservação", "parque", "apa", "rppn", "zona de amortecimento", "uc"],
    summary: "Institui o Sistema Nacional de Unidades de Conservação da Natureza e estabelece critérios e normas para criação, implantação e gestão das unidades de conservação.",
    relevance: "É referência quando a atividade, estudo ou empreendimento se relaciona com unidades de conservação, suas zonas de amortecimento ou objetivos de conservação.",
    url: "https://www.planalto.gov.br/ccivil_03/leis/l9985.htm",
    verified: "out/2026"
  },
  {
    id: "lei-12305-2010",
    title: "Lei nº 12.305/2010 — Política Nacional de Resíduos Sólidos",
    scope: "Federal",
    uf: "BR",
    authority: "Presidência da República",
    themes: ["residuos", "licenciamento", "gestao ambiental"],
    keywords: ["residuos", "resíduos", "pgrs", "lixo", "coleta seletiva", "logistica reversa", "logística reversa", "gerenciamento residuos", "aterro"],
    summary: "Institui a Política Nacional de Resíduos Sólidos e disciplina princípios, objetivos, instrumentos e responsabilidades relacionados à gestão integrada e ao gerenciamento de resíduos sólidos.",
    relevance: "É referência federal para planos e rotinas de gerenciamento, destinação, responsabilidade de geradores e logística reversa.",
    url: "https://www.planalto.gov.br/ccivil_03/_ato2007-2010/2010/lei/l12305.htm",
    verified: "out/2026"
  },
  {
    id: "decreto-10936-2022",
    title: "Decreto nº 10.936/2022 — Regulamento da Política Nacional de Resíduos Sólidos",
    scope: "Federal",
    uf: "BR",
    authority: "Presidência da República",
    themes: ["residuos", "gestao ambiental"],
    keywords: ["residuos", "resíduos", "pnrs", "pgrs", "logistica reversa", "reciclagem", "rejeitos", "destinacao final"],
    summary: "Regulamenta a Lei nº 12.305/2010 e detalha a implementação da Política Nacional de Resíduos Sólidos. O decreto revogou, entre outros atos, o Decreto nº 7.404/2010.",
    relevance: "É a referência regulamentar federal atual cadastrada nesta base para a Política Nacional de Resíduos Sólidos.",
    url: "https://www.planalto.gov.br/ccivil_03/_ato2019-2022/2022/decreto/d10936.htm",
    verified: "out/2026"
  },
  {
    id: "decreto-6660-2008",
    title: "Decreto nº 6.660/2008 — Regulamento da Lei da Mata Atlântica",
    scope: "Federal",
    uf: "BR",
    authority: "Presidência da República",
    themes: ["flora", "supressao", "mata atlantica", "recuperacao"],
    keywords: ["mata atlantica", "mata atlântica", "vegetacao nativa", "supressao", "compensacao", "recuperacao", "inventario"],
    summary: "Regulamenta dispositivos da Lei nº 11.428/2006 relativos à utilização e proteção da vegetação nativa do Bioma Mata Atlântica.",
    relevance: "Complementa a Lei da Mata Atlântica em análises de intervenção, supressão, recuperação e alternativas técnicas e locacionais quando o bioma for aplicável.",
    url: "https://www.planalto.gov.br/ccivil_03/_ato2007-2010/2008/decreto/d6660.htm",
    verified: "out/2026"
  },
  {
    id: "conama-237-1997",
    title: "Resolução CONAMA nº 237/1997 — Licenciamento Ambiental",
    scope: "Federal",
    uf: "BR",
    authority: "CONAMA",
    themes: ["licenciamento", "estudos ambientais", "competencia"],
    keywords: ["licenciamento ambiental", "licenca previa", "licenca instalacao", "licenca operacao", "lp", "li", "lo", "eia rima"],
    summary: "Revisa e complementa procedimentos e critérios utilizados no licenciamento ambiental e define conceitos de licença, estudos ambientais e procedimentos do processo.",
    relevance: "Continua sendo referência procedimental importante e deve ser lida em conjunto com normas posteriores, especialmente a Lei Complementar nº 140/2011 e a Lei nº 15.190/2025.",
    url: "https://conama.mma.gov.br/?id=237%3E&option=com_sisconama&task=arquivo.download",
    verified: "out/2026"
  },
  {
    id: "ba-12932-2014",
    title: "Lei Estadual nº 12.932/2014 — Política Estadual de Resíduos Sólidos da Bahia",
    scope: "Estadual",
    uf: "BA",
    authority: "Estado da Bahia",
    themes: ["residuos", "gestao ambiental", "licenciamento"],
    keywords: ["bahia", "residuos solidos", "resíduos sólidos", "pers ba", "pgrs", "gestao residuos", "coleta seletiva"],
    summary: "Institui a Política Estadual de Resíduos Sólidos da Bahia e estabelece princípios, objetivos, diretrizes e instrumentos para gestão e gerenciamento no território estadual.",
    relevance: "É a referência legal estadual para demandas sobre resíduos sólidos na Bahia. A página oficial consultada também disponibiliza minuta de decreto regulamentador, que não deve ser confundida com norma já promulgada.",
    url: "https://www.ba.gov.br/meioambiente/352/minuta-de-decreto-regulamentador-da-politica-estadual-de-residuos-solidos",
    verified: "out/2026"
  },
  {
    id: "ba-cepram-4327-2013",
    title: "Resolução CEPRAM nº 4.327/2013 e atualizações — Impacto Local na Bahia",
    scope: "Estadual",
    uf: "BA",
    authority: "CEPRAM / SEMA Bahia",
    themes: ["licenciamento", "competencia", "municipal"],
    keywords: ["bahia", "licenciamento municipal", "impacto local", "cepram 4327", "cepram 4420", "gac", "competencia municipal"],
    summary: "Estabelece atividades de impacto local de competência municipal e regras de cooperação federativa na gestão ambiental. O Programa GAC da SEMA registra atualizações e utiliza, entre outras referências, o Anexo Único da Resolução CEPRAM nº 4.420/2015.",
    relevance: "É referência para avaliar o exercício do licenciamento municipal na Bahia, que depende da tipologia e da capacidade institucional do município; a simples localização da atividade no território municipal não resolve a competência.",
    url: "https://www.ba.gov.br/meioambiente/152/programa-gestao-ambiental-compartilhada",
    verified: "out/2026"
  },
  {
    id: "ba-inema-in-003-2022",
    title: "IN INEMA nº 003/2022 — Perfuração de Poços no Aquífero Urucuia",
    scope: "Estadual",
    uf: "BA",
    authority: "INEMA",
    themes: ["recursos_hidricos", "outorga", "agua"],
    keywords: ["bahia", "urucuia", "poco", "poço", "appo", "agua subterranea", "outorga", "perfuracao de poco"],
    summary: "Dispõe sobre procedimentos administrativos e critérios técnicos para Autorização para Perfuração de Poços no contexto definido pela norma para o aquífero Urucuia.",
    relevance: "É referência específica para demandas de perfuração e exploração de água subterrânea abrangidas pelo aquífero Urucuia na Bahia.",
    url: "https://www.ba.gov.br/inema/legislacao/normas-tecnicas-e-portarias",
    verified: "out/2026"
  },
  {
    id: "ba-inema-in-004-2022",
    title: "IN INEMA nº 004/2022 — Perfuração de Poços Tubulares",
    scope: "Estadual",
    uf: "BA",
    authority: "INEMA",
    themes: ["recursos_hidricos", "outorga", "agua"],
    keywords: ["bahia", "poco tubular", "poço tubular", "agua subterranea", "perfuracao", "appo", "outorga"],
    summary: "Dispõe sobre procedimentos administrativos e critérios técnicos para perfuração de poços tubulares destinados à exploração de água subterrânea.",
    relevance: "É referência estadual para verificar requisitos administrativos e técnicos antes da perfuração de poços tubulares na Bahia.",
    url: "https://www.ba.gov.br/inema/legislacao/normas-tecnicas-e-portarias",
    verified: "out/2026"
  },
  {
    id: "ba-inema-22181-2021",
    title: "Portaria INEMA nº 22.181/2021 — Medição de Usos de Recursos Hídricos",
    scope: "Estadual",
    uf: "BA",
    authority: "INEMA",
    themes: ["recursos_hidricos", "outorga", "monitoramento"],
    keywords: ["bahia", "medicao agua", "medição água", "monitoramento vazao", "outorga", "captacao", "intervencao recurso hidrico"],
    summary: "Estabelece critérios para implantação de sistemas de medição destinados ao monitoramento de usos e intervenções em recursos hídricos no Estado da Bahia.",
    relevance: "Pode ser relevante para usuários outorgados sujeitos a requisitos de medição e monitoramento quantitativo dos usos de água.",
    url: "https://www.ba.gov.br/inema/sites/site-inema/files/migracao_2024/arquivos/wp-content/files/22.181_DE_22_DE_JANEIRO_DE_2021_-_Implantao_de_sistema_de_medio_para_monitoramento_dos_usos_e_intervenes_em_recursos_hdricos.pdf",
    verified: "out/2026"
  },
  {
    id: "ba-inema-25753-2022",
    title: "Portaria INEMA nº 25.753/2022 — Pesquisa em Unidades de Conservação Estaduais",
    scope: "Estadual",
    uf: "BA",
    authority: "INEMA",
    themes: ["unidades_conservacao", "pesquisa_uc", "fauna", "flora"],
    keywords: ["bahia", "pesquisa cientifica", "pesquisa científica", "unidade de conservacao", "coleta biologica", "atividade didatica", "uc estadual"],
    summary: "Estabelece critérios e procedimentos para pesquisas científicas e atividades didáticas em unidades de conservação instituídas pelo poder público estadual da Bahia.",
    relevance: "É referência quando estudos e coletas ocorrerem em UCs estaduais administradas pelo INEMA. Outras autorizações podem ser necessárias conforme o objeto da pesquisa e as espécies envolvidas.",
    url: "https://www.ba.gov.br/inema/autorizacao-para-pesquisas-e-estudos-cientificos-em-ucs",
    verified: "out/2026"
  },
  {
    id: "ba-inema-22352-2021",
    title: "Portaria INEMA nº 22.352/2021 — Comunicação de Emergência Ambiental",
    scope: "Estadual",
    uf: "BA",
    authority: "INEMA",
    themes: ["emergencia", "licenciamento", "gestao ambiental"],
    keywords: ["bahia", "emergencia ambiental", "emergência ambiental", "acidente ambiental", "vazamento", "derramamento", "comunicacao inema"],
    summary: "Estabelece procedimentos para comunicação ao INEMA de situações de emergência ambiental.",
    relevance: "É referência estadual para empreendimentos e responsáveis que precisem verificar o procedimento de comunicação de ocorrências ambientais emergenciais ao INEMA.",
    url: "https://www.ba.gov.br/inema/legislacao/normas-tecnicas-e-portarias",
    verified: "out/2026"
  },
  {
    id: "ba-inema-19090-2019",
    title: "Portaria INEMA nº 19.090/2019 — Árvores Nativas Isoladas em Grave Risco",
    scope: "Estadual",
    uf: "BA",
    authority: "INEMA",
    themes: ["flora", "supressao", "emergencia"],
    keywords: ["bahia", "arvore isolada", "árvore isolada", "grave risco", "iminente perigo", "queda de arvore", "corte emergencial"],
    summary: "Estabelece procedimento específico para retirada de árvores nativas isoladas em caso de grave risco e iminente perigo à segurança de pessoas e bens, com exigência de manutenção de registros fotográficos nas hipóteses abrangidas.",
    relevance: "É uma exceção específica para situações de grave risco; não deve ser interpretada como dispensa geral de autorização para corte de árvores nativas isoladas.",
    url: "https://www.ba.gov.br/inema/sites/site-inema/files/migracao_2024/arquivos/wp-content/files/Portaria_INEMA_19.090_-_Retirada_de_rvores_nativas_isoladas_em_caso_de_grave_risco_e_iminente_perigo_a_segurana19.pdf",
    verified: "out/2026"
  },
  {
    id: "al-6787-2006",
    title: "Lei Estadual nº 6.787/2006 — Licenciamento e Infrações Ambientais de Alagoas",
    scope: "Estadual",
    uf: "AL",
    authority: "Estado de Alagoas / IMA-AL",
    themes: ["licenciamento", "responsabilidade", "gestao ambiental"],
    keywords: ["alagoas", "ima al", "licenciamento ambiental", "licenca", "autorizacao", "infracao ambiental"],
    summary: "Disciplina competências e procedimentos estaduais relacionados ao licenciamento, controle, fiscalização, infrações e sanções ambientais em Alagoas, com alterações posteriores consolidadas pelo IMA.",
    relevance: "É uma referência central para o licenciamento e a atuação fiscalizatória estadual em Alagoas.",
    url: "https://www2.ima.al.gov.br/wp-content/uploads/legislacao/leis-estaduais/Lei%20n%C2%BA%206.787%20ATUAL.pdf",
    verified: "out/2026"
  },
  {
    id: "al-cepram-10-2018",
    title: "Resolução CEPRAM nº 10/2018 — Licenciamento Ambiental em Alagoas",
    scope: "Estadual",
    uf: "AL",
    authority: "CEPRAM / IMA-AL",
    themes: ["licenciamento", "estudos ambientais"],
    keywords: ["alagoas", "cepram 10 2018", "ima al", "licenciamento", "atividade potencialmente poluidora", "eia rima"],
    summary: "Define procedimentos de aprovação dos processos de licenciamento de competência estadual e a listagem de atividades potencialmente causadoras de degradação ambiental passíveis de licenciamento pelo IMA/AL.",
    relevance: "É referência operacional importante para enquadramento e procedimentos de licenciamento estadual em Alagoas.",
    url: "https://www2.ima.al.gov.br/wp-content/uploads/legislacao/resolucoes-cepram/2018/RESOLUC%CC%A7A%CC%83O%20CEPRAM%20N%C2%BA%2010.2018--LICENCIAMENTO%20AMBIENTAL.pdf",
    verified: "out/2026"
  },
  {
    id: "al-5965-1997",
    title: "Lei Estadual nº 5.965/1997 — Política Estadual de Recursos Hídricos de Alagoas",
    scope: "Estadual",
    uf: "AL",
    authority: "Estado de Alagoas",
    themes: ["recursos_hidricos", "outorga", "agua"],
    keywords: ["alagoas", "recursos hidricos", "água", "outorga", "bacia hidrografica", "captacao"],
    summary: "Institui a política e os instrumentos estaduais de gestão de recursos hídricos em Alagoas, incluindo planejamento, informação e mecanismos de uso da água.",
    relevance: "É referência estadual para demandas de uso, gestão e regularização de recursos hídricos em Alagoas.",
    url: "https://www2.ima.al.gov.br/wp-content/uploads/legislacao/leis-estaduais/LEI%20N%C2%BA%205.965%2C%20DE%2010%20DE%20NOVEMBRO%20DE%201997..pdf",
    verified: "out/2026"
  },
  {
    id: "al-7749-2015",
    title: "Lei Estadual nº 7.749/2015 — Resíduos Sólidos e Inclusão Produtiva de Alagoas",
    scope: "Estadual",
    uf: "AL",
    authority: "Estado de Alagoas",
    themes: ["residuos", "gestao ambiental"],
    keywords: ["alagoas", "residuos solidos", "resíduos sólidos", "coleta seletiva", "gerenciamento residuos", "inclusao produtiva"],
    summary: "Institui a Política Estadual de Resíduos Sólidos e Inclusão Produtiva e dispõe sobre diretrizes de gestão integrada e gerenciamento de resíduos no estado.",
    relevance: "É referência estadual para planos, gestão e responsabilidades relacionadas a resíduos sólidos em Alagoas.",
    url: "https://www2.ima.al.gov.br/wp-content/uploads/legislacao/leis-estaduais/LEI%20N%C2%BA%207.749%2C%20DE%2013%20DE%20OUTUBRO%20DE%202015..pdf",
    verified: "out/2026"
  },
  {
    id: "ce-coema-02-2019",
    title: "Resolução COEMA nº 02/2019 — Licenciamento Ambiental no Ceará",
    scope: "Estadual",
    uf: "CE",
    authority: "COEMA / SEMACE",
    themes: ["licenciamento", "estudos ambientais"],
    keywords: ["ceara", "ceará", "coema 02 2019", "semace", "licenciamento ambiental", "licenca", "eia rima"],
    summary: "Estabelece procedimentos, critérios e parâmetros para o licenciamento ambiental no Ceará. A norma recebeu alterações posteriores, inclusive pela Resolução COEMA nº 10/2020.",
    relevance: "É uma das referências estaduais centrais para enquadramento e procedimentos de licenciamento no Ceará; a versão e alterações aplicáveis devem ser conferidas no caso concreto.",
    url: "https://www.semace.ce.gov.br/wp-content/uploads/sites/46/2019/05/Resolucao-COEMA-02-de-2019.pdf",
    verified: "out/2026"
  },
  {
    id: "ce-19240-2025",
    title: "Lei Estadual nº 19.240/2025 — Licenciamento Ambiental Municipal no Ceará",
    scope: "Estadual",
    uf: "CE",
    authority: "Estado do Ceará",
    themes: ["licenciamento", "competencia", "municipal"],
    keywords: ["ceara", "ceará", "licenciamento municipal", "impacto local", "competencia municipal", "municipio licenciador"],
    summary: "Estabelece critérios para que os municípios do Ceará exerçam atribuições de licenciamento ambiental de intervenções de impacto local. A Lei nº 19.806/2026 alterou a norma, incluindo regras de transição e adequação municipal.",
    relevance: "É referência atual para verificar se e em quais condições um município cearense pode exercer o licenciamento ambiental local.",
    url: "https://www2.al.ce.gov.br/legislativo/legislacao5/leis2026/19806.htm",
    verified: "out/2026"
  },
  {
    id: "ce-14844-2010",
    title: "Lei Estadual nº 14.844/2010 — Política Estadual de Recursos Hídricos do Ceará",
    scope: "Estadual",
    uf: "CE",
    authority: "Estado do Ceará / SRH",
    themes: ["recursos_hidricos", "outorga", "agua"],
    keywords: ["ceara", "ceará", "recursos hidricos", "outorga", "agua", "sigerh", "captacao"],
    summary: "Dispõe sobre a Política Estadual de Recursos Hídricos e institui o Sistema Integrado de Gestão de Recursos Hídricos do Ceará.",
    relevance: "É referência estadual para gestão, planejamento e regularização de usos de recursos hídricos no Ceará.",
    url: "https://www.srh.ce.gov.br/leis-2010/",
    verified: "out/2026"
  },
  {
    id: "ce-12488-1995",
    title: "Lei Estadual nº 12.488/1995 — Política Florestal do Ceará",
    scope: "Estadual",
    uf: "CE",
    authority: "Estado do Ceará / SEMACE",
    themes: ["flora", "florestal", "supressao", "biodiversidade"],
    keywords: ["ceara", "ceará", "politica florestal", "manejo florestal", "vegetacao", "produto florestal", "supressao"],
    summary: "Dispõe sobre a Política Florestal do Estado do Ceará e estabelece bases estaduais para proteção, uso e gestão dos recursos florestais.",
    relevance: "É referência para demandas relacionadas a vegetação, manejo e produtos florestais no Ceará, devendo ser lida em conjunto com a legislação federal vigente.",
    url: "https://www.semace.ce.gov.br/wp-content/uploads/sites/46/2018/12/coletanea_de_legislacao_ambiental.pdf",
    verified: "out/2026"
  },
  {
    id: "ma-sema-116-2015",
    title: "Portaria SEMA nº 116/2015 — Procedimentos de Licenciamento no Maranhão",
    scope: "Estadual",
    uf: "MA",
    authority: "SEMA Maranhão",
    themes: ["licenciamento", "gestao ambiental"],
    keywords: ["maranhao", "maranhão", "sema ma", "sigla", "licenciamento", "licenca previa", "licenca instalacao", "licenca operacao"],
    summary: "Estabelece procedimentos administrativos utilizados pela SEMA/MA para requerimentos de licenciamento por meio do sistema SIGLA, conforme referenciado nos serviços oficiais do órgão.",
    relevance: "É referência operacional para protocolar e acompanhar modalidades de licenciamento estadual no Maranhão.",
    url: "https://www.sema.ma.gov.br/servicos/obter-licenca-previa-lp",
    verified: "out/2026"
  },
  {
    id: "ma-sema-123-2015",
    title: "Portaria SEMA nº 123/2015 — Dispensa de Licenciamento Ambiental no Maranhão",
    scope: "Estadual",
    uf: "MA",
    authority: "SEMA Maranhão",
    themes: ["licenciamento", "regularizacao"],
    keywords: ["maranhao", "maranhão", "dispensa licenciamento", "dla", "sema ma", "porte", "potencial poluidor"],
    summary: "É a referência indicada pela SEMA/MA para a Dispensa de Licenciamento Ambiental, aplicável conforme características, porte e potencial poluidor ou degradador da atividade.",
    relevance: "Ajuda a verificar hipóteses de dispensa no âmbito estadual; a dispensa deve ser confirmada pelo enquadramento aplicável e não presumida apenas pelo porte aparente da atividade.",
    url: "https://www.sema.ma.gov.br/servicos/solicitar-dispensa-de-licenciamento-ambiental-dla",
    verified: "out/2026"
  },
  {
    id: "ma-sema-69-2020",
    title: "Portaria SEMA nº 069/2020 — Processos de Outorga no Maranhão",
    scope: "Estadual",
    uf: "MA",
    authority: "SEMA Maranhão",
    themes: ["recursos_hidricos", "outorga", "agua"],
    keywords: ["maranhao", "maranhão", "outorga", "agua", "poco", "captação", "sigla", "agua subterranea"],
    summary: "Orienta a abertura, pelo SIGLA, de processos relacionados a autorização de perfuração de poço, outorga de direito de uso de águas superficiais ou subterrâneas, outorga simplificada e declaração de inexigibilidade.",
    relevance: "É referência operacional para regularização do uso da água no Maranhão em conjunto com as resoluções do Conselho Estadual de Recursos Hídricos aplicáveis.",
    url: "https://www.sema.ma.gov.br/servicos/obter-autorizacao-de-uso-da-agua",
    verified: "out/2026"
  },
  {
    id: "ma-sema-079-2016",
    title: "Portaria SEMA nº 079/2016 — Manejo de Fauna no Licenciamento do Maranhão",
    scope: "Estadual",
    uf: "MA",
    authority: "SEMA Maranhão",
    themes: ["fauna", "levantamento", "monitoramento", "resgate", "afugentamento", "captura", "destinacao"],
    keywords: ["maranhao", "maranhão", "fauna", "levantamento fauna", "monitoramento fauna", "resgate fauna", "afugentamento", "captura", "transporte fauna"],
    summary: "Dispõe sobre procedimentos relativos à autorização de coleta, captura e transporte de fauna silvestre necessários a levantamento, monitoramento, resgate, afugentamento e destinação no licenciamento ambiental da SEMA/MA.",
    relevance: "É referência estadual diretamente relacionada às atividades de fauna em processos de licenciamento no Maranhão.",
    url: "https://www.sema.ma.gov.br/portarias",
    verified: "out/2026"
  },
  {
    id: "pb-4335-1981",
    title: "Lei Estadual nº 4.335/1981 — Prevenção e Controle da Poluição na Paraíba",
    scope: "Estadual",
    uf: "PB",
    authority: "Estado da Paraíba / SUDEMA",
    themes: ["licenciamento", "gestao ambiental", "responsabilidade"],
    keywords: ["paraiba", "paraíba", "sudema", "poluicao", "poluição", "controle ambiental", "licenciamento"],
    summary: "Dispõe sobre prevenção e controle da poluição ambiental na Paraíba e estabelece atribuições do COPAM e da SUDEMA na defesa dos recursos ambientais.",
    relevance: "Integra a base estadual de controle ambiental e fiscalização na Paraíba.",
    url: "https://sudema.pb.gov.br/consultas/downloads/arquivos-copam/lei_4335_1981_dispoe_sobre_prevencao_e_controle_da_poluicao_ambiental_e_estabelece_normas_disciplinadoras_da_especie.pdf",
    verified: "out/2026"
  },
  {
    id: "pb-decreto-41560-2021",
    title: "Decreto Estadual nº 41.560/2021 — Licenciamento Ambiental na Paraíba",
    scope: "Estadual",
    uf: "PB",
    authority: "Estado da Paraíba / SUDEMA",
    themes: ["licenciamento", "competencia", "estudos ambientais"],
    keywords: ["paraiba", "paraíba", "decreto 41560", "sudema", "licenciamento", "tipologias licenca", "prazo licença"],
    summary: "Regulamenta a Lei Complementar nº 140/2011 no âmbito estadual e disciplina licenciamento ambiental, tipologias de licenças e prazos de validade na Paraíba.",
    relevance: "É uma referência estadual central para modalidades e procedimentos do licenciamento ambiental da Paraíba.",
    url: "https://sudema.pb.gov.br/institucional/copam-1/legislacao-pertinente",
    verified: "out/2026"
  },
  {
    id: "pb-copam-5302-2022",
    title: "Deliberação COPAM nº 5.302/2022 — Licenciamento Ambiental Municipal na Paraíba",
    scope: "Estadual",
    uf: "PB",
    authority: "COPAM / SUDEMA",
    themes: ["licenciamento", "competencia", "municipal"],
    keywords: ["paraiba", "paraíba", "licenciamento municipal", "impacto local", "copam 5302", "omma", "habilitacao municipio"],
    summary: "Estabelece tipologias para licenciamento ambiental municipal de impacto local e requisitos e procedimentos para habilitação dos municípios.",
    relevance: "É referência para verificar a competência municipal para licenciamento na Paraíba; o município precisa atender aos requisitos de habilitação previstos.",
    url: "https://sudema.pb.gov.br/institucional/copam-1/licenciamento-ambiental-municipal",
    verified: "out/2026"
  },
  {
    id: "pb-6002-1994",
    title: "Lei Estadual nº 6.002/1994 — Código Florestal da Paraíba",
    scope: "Estadual",
    uf: "PB",
    authority: "Estado da Paraíba / SUDEMA",
    themes: ["flora", "florestal", "supressao", "biodiversidade"],
    keywords: ["paraiba", "paraíba", "codigo florestal", "código florestal", "vegetacao", "floresta", "reposicao florestal"],
    summary: "Institui o Código Florestal do Estado da Paraíba e estabelece disposições estaduais relacionadas à proteção e uso dos recursos florestais.",
    relevance: "É referência estadual para demandas florestais na Paraíba, em conjunto com a legislação federal superveniente aplicável.",
    url: "https://sudema.pb.gov.br/institucional/copam-1/legislacao-pertinente",
    verified: "out/2026"
  },
  {
    id: "pb-6308-1996",
    title: "Lei Estadual nº 6.308/1996 — Política Estadual de Recursos Hídricos da Paraíba",
    scope: "Estadual",
    uf: "PB",
    authority: "Estado da Paraíba",
    themes: ["recursos_hidricos", "outorga", "agua"],
    keywords: ["paraiba", "paraíba", "recursos hidricos", "outorga", "agua", "bacia hidrografica", "aesa"],
    summary: "Institui a Política Estadual de Recursos Hídricos e suas diretrizes, estruturando a gestão das águas no Estado da Paraíba.",
    relevance: "É referência estadual para uso, planejamento e regularização de recursos hídricos na Paraíba.",
    url: "https://sudema.pb.gov.br/informacoes-ao-cidadao-1/unidades-de-conservacao/arquivos/mata-do-xem-xem/pm_mata_xemxem_revisadofinal.pdf",
    verified: "out/2026"
  },
  {
    id: "pe-14249-2010",
    title: "Lei Estadual nº 14.249/2010 — Licenciamento Ambiental de Pernambuco",
    scope: "Estadual",
    uf: "PE",
    authority: "Estado de Pernambuco / CPRH",
    themes: ["licenciamento", "responsabilidade", "gestao ambiental"],
    keywords: ["pernambuco", "cprh", "licenciamento ambiental", "infracao", "sanção administrativa", "licenca"],
    summary: "Dispõe sobre licenciamento ambiental, infrações e sanções administrativas ao meio ambiente em Pernambuco. A CPRH disponibiliza versão com alterações posteriores, incluindo a Lei nº 17.672/2022.",
    relevance: "É uma referência estadual central para licenciamento e sanções administrativas ambientais em Pernambuco.",
    url: "https://www2.cprh.pe.gov.br/2010/12/17/lei-n-14-249-de-17-de-dezembro-de-2010-com-as-alteracoes-da-lei-no-17-672-de-10-de-janeiro-de-2022/",
    verified: "out/2026"
  },
  {
    id: "pe-consema-01-2018",
    title: "Resolução CONSEMA nº 01/2018 — Licenciamento Municipal em Pernambuco",
    scope: "Estadual",
    uf: "PE",
    authority: "CONSEMA / CPRH",
    themes: ["licenciamento", "competencia", "municipal"],
    keywords: ["pernambuco", "licenciamento municipal", "impacto local", "consema 01 2018", "municipio habilitado"],
    summary: "Define tipologias consideradas de impacto local para fins de licenciamento ambiental municipal e critérios relacionados ao exercício da competência pelos municípios.",
    relevance: "É referência para verificar competência municipal em Pernambuco. A CPRH mantém lista pública dos municípios legalmente habilitados.",
    url: "https://www2.cprh.pe.gov.br/2018/10/19/resolucao-consema-no-01-2018-de-19-de-outubro-de-2018-2/",
    verified: "out/2026"
  },
  {
    id: "pe-cprh-in-004-2021",
    title: "IN CPRH nº 004/2021 — Supressão de Indivíduos Isolados Nativos",
    scope: "Estadual",
    uf: "PE",
    authority: "CPRH",
    themes: ["flora", "supressao", "florestal"],
    keywords: ["pernambuco", "cprh", "arvore isolada", "árvore isolada", "supressao individuo isolado", "reposicao florestal"],
    summary: "Dispõe sobre procedimentos para autorização de supressão de indivíduos isolados de espécies nativas, nas condições definidas pela instrução normativa.",
    relevance: "É referência específica para intervenções em indivíduos nativos isolados em Pernambuco e não deve ser generalizada para outras formações vegetais ou áreas protegidas.",
    url: "https://www2.cprh.pe.gov.br/2021/03/25/instrucao-normativa-cprh-no-004-2021/",
    verified: "out/2026"
  },
  {
    id: "pe-apac-cprh-001-2017",
    title: "Portaria Conjunta APAC/CPRH nº 001/2017 — Licença Ambiental e Outorga",
    scope: "Estadual",
    uf: "PE",
    authority: "APAC / CPRH",
    themes: ["recursos_hidricos", "outorga", "licenciamento"],
    keywords: ["pernambuco", "apac", "cprh", "outorga", "licenciamento", "manancial estadual", "uso da agua"],
    summary: "Estabelece condições e procedimentos articulados para obtenção de licença ambiental e outorga de uso dos recursos hídricos em mananciais de domínio do Estado de Pernambuco.",
    relevance: "É referência para demandas em que licenciamento e uso da água precisam ser analisados de forma coordenada em Pernambuco.",
    url: "https://www2.cprh.pe.gov.br/2017/02/03/portaria-conjunta-apac-cprh-no-001-2017/",
    verified: "out/2026"
  },
  {
    id: "pi-5165-2000",
    title: "Lei Estadual nº 5.165/2000 — Política Estadual de Recursos Hídricos do Piauí",
    scope: "Estadual",
    uf: "PI",
    authority: "Estado do Piauí / SEMARH",
    themes: ["recursos_hidricos", "outorga", "agua"],
    keywords: ["piaui", "piauí", "recursos hidricos", "outorga", "agua", "cerh", "bacia hidrografica"],
    summary: "Dispõe sobre a Política Estadual de Recursos Hídricos e institui o Sistema Estadual de Gerenciamento de Recursos Hídricos e o Conselho Estadual de Recursos Hídricos.",
    relevance: "É referência estadual para planejamento, uso e regularização de recursos hídricos no Piauí.",
    url: "https://www.semarh.pi.gov.br/conselhos/cerh",
    verified: "out/2026"
  },
  {
    id: "pi-5178-2000",
    title: "Lei Estadual nº 5.178/2000 — Política Florestal do Piauí",
    scope: "Estadual",
    uf: "PI",
    authority: "Estado do Piauí / SEMARH",
    themes: ["flora", "florestal", "supressao", "biodiversidade"],
    keywords: ["piaui", "piauí", "politica florestal", "vegetacao", "floresta", "manejo florestal", "supressao"],
    summary: "Dispõe sobre a Política Florestal do Estado do Piauí e estabelece bases para proteção e gestão dos recursos florestais estaduais.",
    relevance: "É referência estadual para demandas de vegetação, manejo e recursos florestais no Piauí, em conjunto com a legislação federal aplicável.",
    url: "https://www.semarh.pi.gov.br/legislacao",
    verified: "out/2026"
  },
  {
    id: "pi-consema-046-2022",
    title: "Resolução CONSEMA nº 046/2022 — Enquadramento do Licenciamento no Piauí",
    scope: "Estadual",
    uf: "PI",
    authority: "CONSEMA / SEMARH Piauí",
    themes: ["licenciamento", "estudos ambientais", "competencia"],
    keywords: ["piaui", "piauí", "consema 046", "licenciamento ambiental", "enquadramento", "porte potencial poluidor"],
    summary: "Altera e acrescenta dispositivos à Resolução CONSEMA nº 040/2021 e disponibiliza versão consolidada do enquadramento do licenciamento ambiental no Piauí.",
    relevance: "É referência atual cadastrada para verificar enquadramento de atividades e empreendimentos sujeitos a licenciamento estadual no Piauí.",
    url: "https://www.semarh.pi.gov.br/conselhos/consema",
    verified: "out/2026"
  },
  {
    id: "pi-conjunta-consema-cerh-001-2025",
    title: "Resolução Conjunta CONSEMA/CERH nº 001/2025 — Barragens no Piauí",
    scope: "Estadual",
    uf: "PI",
    authority: "CONSEMA / CERH / SEMARH Piauí",
    themes: ["licenciamento", "recursos_hidricos", "outorga", "emergencia"],
    keywords: ["piaui", "piauí", "barragem", "outorga", "licenciamento barragem", "seguranca barragem", "psb"],
    summary: "Estabelece procedimentos gerais de licenciamento, regularização ambiental e outorga para barragens de acumulação de água de competência estadual.",
    relevance: "É referência específica para projetos e regularização de barragens de acumulação no Piauí.",
    url: "https://www.semarh.pi.gov.br/conselhos/consema",
    verified: "out/2026"
  },
  {
    id: "rn-lc-272-2004",
    title: "Lei Complementar Estadual nº 272/2004 — Política e Sistema Estadual do Meio Ambiente do RN",
    scope: "Estadual",
    uf: "RN",
    authority: "Estado do Rio Grande do Norte / IDEMA",
    themes: ["licenciamento", "gestao ambiental", "unidades_conservacao", "responsabilidade"],
    keywords: ["rio grande do norte", "rn", "idema", "licenciamento", "politica estadual meio ambiente", "compensacao ambiental"],
    summary: "Dispõe sobre a Política e o Sistema Estadual do Meio Ambiente do Rio Grande do Norte, infrações e sanções administrativas, unidades estaduais de conservação e medidas compensatórias ambientais.",
    relevance: "É uma referência estrutural da gestão e do licenciamento ambiental estadual no Rio Grande do Norte.",
    url: "https://diariooficial.rn.gov.br/dei/dorn3/documentos/00000001/20220217/757999.htm",
    verified: "out/2026"
  },
  {
    id: "rn-6908-1996",
    title: "Lei Estadual nº 6.908/1996 — Política Estadual de Recursos Hídricos do RN",
    scope: "Estadual",
    uf: "RN",
    authority: "Estado do Rio Grande do Norte / IGARN",
    themes: ["recursos_hidricos", "outorga", "agua"],
    keywords: ["rio grande do norte", "rn", "igarn", "recursos hidricos", "outorga", "agua", "bacia hidrografica"],
    summary: "Institui a Política Estadual de Recursos Hídricos e o Sistema Integrado de Gestão dos Recursos Hídricos do Rio Grande do Norte.",
    relevance: "É referência estadual para planejamento, proteção e regularização dos usos de água no Rio Grande do Norte.",
    url: "https://webdisk.diariooficial.rn.gov.br/Jornal/12026-04-17.pdf",
    verified: "out/2026"
  },
  {
    id: "se-5858-2006",
    title: "Lei Estadual nº 5.858/2006 — Política Estadual do Meio Ambiente de Sergipe",
    scope: "Estadual",
    uf: "SE",
    authority: "Estado de Sergipe / ADEMA",
    themes: ["licenciamento", "gestao ambiental", "fauna", "flora", "biodiversidade"],
    keywords: ["sergipe", "adema", "politica estadual meio ambiente", "licenciamento", "fauna", "flora", "poluicao"],
    summary: "Institui a Política Estadual do Meio Ambiente e o Sistema Estadual do Meio Ambiente de Sergipe, estabelecendo bases para proteção, controle e gestão ambiental.",
    relevance: "É referência estrutural para a política e os instrumentos de gestão ambiental em Sergipe.",
    url: "https://adema.se.gov.br/wp-content/uploads/2017/03/lei_n_5.858-06.pdf",
    verified: "out/2026"
  },
  {
    id: "se-8497-2018",
    title: "Lei Estadual nº 8.497/2018, alterada pela Lei nº 8.607/2019 — Licenciamento Ambiental em Sergipe",
    scope: "Estadual",
    uf: "SE",
    authority: "Estado de Sergipe / ADEMA",
    themes: ["licenciamento", "estudos ambientais"],
    keywords: ["sergipe", "adema", "licenciamento ambiental", "lei 8497", "lei 8607", "licenca ambiental"],
    summary: "Dispõe sobre o licenciamento ambiental no Estado de Sergipe e recebeu alterações pela Lei nº 8.607/2019.",
    relevance: "É referência estadual central para modalidades e procedimentos de licenciamento ambiental em Sergipe.",
    url: "https://www.adema.se.gov.br/wp-content/uploads/2024/03/Lei-estadual-8497.2018-licenciamento-ambiental.pdf",
    verified: "out/2026"
  },
  {
    id: "se-adema-4-2020",
    title: "Portaria ADEMA-SE nº 4/2020 — Processo de Licenciamento em Sergipe",
    scope: "Estadual",
    uf: "SE",
    authority: "ADEMA",
    themes: ["licenciamento", "gestao ambiental"],
    keywords: ["sergipe", "adema", "portaria 4 2020", "processo licenciamento", "procedimento licenciamento"],
    summary: "Dispõe sobre o processo de licenciamento e seu procedimento segundo a Lei Estadual nº 8.497/2018 e as modificações implementadas pela Lei nº 8.607/2019.",
    relevance: "É referência operacional complementar para os procedimentos de licenciamento conduzidos pela ADEMA.",
    url: "https://adema.se.gov.br/legislacao-e-portarias-concurso-da-adema/",
    verified: "out/2026"
  },
  {
    id: "se-3870-1997",
    title: "Lei Estadual nº 3.870/1997 — Política Estadual de Recursos Hídricos de Sergipe",
    scope: "Estadual",
    uf: "SE",
    authority: "Estado de Sergipe",
    themes: ["recursos_hidricos", "outorga", "agua"],
    keywords: ["sergipe", "recursos hidricos", "outorga", "agua", "poco", "captação", "bacia hidrografica"],
    summary: "Dispõe sobre a Política Estadual de Recursos Hídricos e o Sistema Estadual de Gerenciamento de Recursos Hídricos de Sergipe.",
    relevance: "É referência estadual para uso, outorga, planejamento e gestão das águas superficiais e subterrâneas em Sergipe.",
    url: "https://www.adema.se.gov.br/wp-content/uploads/2024/10/LEI-N-3-870-DE-25-DE-SETEMBRO-DE-1997-Disp-e-sobre-a-Pol-tica-Estadual-de-Recursos-H-dricos-e-o-Sistema-Estadual-de-Gerenciamento-de-Recursos-H-dricos-e-d-outras-providencia-pdf.pdf",
    verified: "out/2026"
  },
  {
    id: "se-conjunta-32-2024",
    title: "Portaria Conjunta nº 32/2024 — Integração entre Outorga e Licenciamento em Sergipe",
    scope: "Estadual",
    uf: "SE",
    authority: "SEM/SEMAC / ADEMA",
    themes: ["recursos_hidricos", "outorga", "licenciamento"],
    keywords: ["sergipe", "outorga", "licenciamento", "portaria conjunta 32 2024", "recursos hidricos", "adema"],
    summary: "Estabelece procedimentos de integração entre atos regulatórios vinculados à outorga de recursos hídricos e o licenciamento ambiental estadual.",
    relevance: "É referência prática para processos em Sergipe que envolvam simultaneamente uso de recursos hídricos e licenciamento ambiental.",
    url: "https://adema.se.gov.br/semac-e-adema-integram-protocolos-para-agilizar-outorga-de-recursos-hidricos-e-licenciamento-ambiental/",
    verified: "out/2026"
  },
  {
    id: "se-5857-2006",
    title: "Lei Estadual nº 5.857/2006 — Gestão Integrada de Resíduos Sólidos de Sergipe",
    scope: "Estadual",
    uf: "SE",
    authority: "Estado de Sergipe",
    themes: ["residuos", "gestao ambiental"],
    keywords: ["sergipe", "residuos solidos", "resíduos sólidos", "gestao integrada", "gerenciamento residuos"],
    summary: "Dispõe sobre a Política Estadual de Gestão Integrada de Resíduos Sólidos em Sergipe.",
    relevance: "É referência estadual para gestão e gerenciamento de resíduos sólidos, em conjunto com a Política Nacional de Resíduos Sólidos e suas normas posteriores.",
    url: "https://adema.se.gov.br/leis/",
    verified: "out/2026"
  }

];
